/*
* This header is generated by classdump-dyld 0.7
* on Sunday, November 22, 2015 at 10:28:31 PM Eastern Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libnfshared.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface NFJSONEncoder : NSObject
+(id)encoder;
-(id)stringFromArray:(id)arg1 ;
-(id)stringFromDictionary:(id)arg1 ;
-(id)_JSONCompatibleArray:(id)arg1 ;
-(id)_JSONCompatibleDictionary:(id)arg1 ;
@end

