/*
* This header is generated by classdump-dyld 0.7
* on Sunday, November 22, 2015 at 10:28:31 PM Eastern Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libnfshared.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol NFPowerObserverDelegate;
#import <libnfshared.dylib/libnfshared.dylib-Structs.h>
@interface NFPowerObserver : NSObject {

	id<NFPowerObserverDelegate> _delegate;
	unsigned _powerNotificationConnection;
	IONotificationPortRef _powerNotificationPort;
	unsigned _powerNotificationNotifier;
	BOOL _willSleep;

}

@property (readonly) BOOL willSleep;              //@synthesize willSleep=_willSleep - In the implementation block
-(void)dealloc;
-(id)initWithDelegate:(id)arg1 ;
-(void)unregisterForEvents;
-(BOOL)registerForEvents;
-(void)_powerNotificationMessage:(unsigned)arg1 argument:(void*)arg2 ;
-(BOOL)willSleep;
@end

