//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBSteppedAnimationTimingFunctionCalculator.h"

@interface _SBMinusPageStepper : SBSteppedAnimationTimingFunctionCalculator
{
}

@property(readonly, nonatomic) double pageControlAlpha;
@property(readonly, nonatomic) double backgroundBlurAlpha;
- (id)init;

@end

