//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SBAlertWindowViewController;

@protocol SBAlertWindowViewControllerDelegate <NSObject>
- (unsigned long long)defaultSupportedInterfaceOrientationsForAlertWindowViewController:(SBAlertWindowViewController *)arg1;
- (long long)defaultInterfaceOrientationForPresentationOfAlertWindowViewController:(SBAlertWindowViewController *)arg1;
- (_Bool)defaultShouldAutorotateForAlertWindowViewController:(SBAlertWindowViewController *)arg1;
@end

