//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class SBBulletinRootView, SBBulletinWindowController, _SBBulletinRootViewControllerTransitionContext;

@interface SBBulletinRootViewController : UIViewController
{
    SBBulletinRootView *_rootView;
    SBBulletinWindowController *_windowController;
    _SBBulletinRootViewControllerTransitionContext *_activeTransitionContext;
}

- (void)_getRotationContentSettings:(CDStruct_e950349b *)arg1;
- (_Bool)shouldAutomaticallyForwardRotationMethods;
- (_Bool)shouldAutomaticallyForwardAppearanceMethods;
- (_Bool)wantsFullScreenLayout;
- (void)dealloc;
- (void)loadView;
- (id)initWithBulletinWindowController:(id)arg1;

@end

