//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBSceneManager.h"

@interface SBCarDisplaySceneManager : SBSceneManager
{
}

- (_Bool)_handleAction:(id)arg1 forScene:(id)arg2;
- (id)_sceneWindowLayoutStrategy;
- (id)_newLayoutControllerForDisplay:(id)arg1;

@end

