//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SBCommandTabViewControllerDelegate.h"

@class FBUIApplicationSceneDeactivationAssertion, NSString, NSTimer, SBCommandTabViewController, SBWindow;

@interface SBCommandTabController : NSObject <SBCommandTabViewControllerDelegate>
{
    SBCommandTabViewController *_commandTabViewController;
    NSTimer *_timer;
    FBUIApplicationSceneDeactivationAssertion *_resignActiveAssertion;
    SBWindow *_window;
}

+ (id)keyCommands;
+ (id)sharedInstance;
@property(readonly, retain, nonatomic) SBWindow *window; // @synthesize window=_window;
- (void)_clearTimer;
- (void)_showWindow:(_Bool)arg1;
- (void)_showCommandTabBarAfterTimer:(id)arg1;
- (void)_activateWithForwardDirection:(_Bool)arg1;
- (void)viewControllerWantsDismissal:(id)arg1;
- (void)viewController:(id)arg1 selectedApplicationWithBundleID:(id)arg2;
- (void)launchCurrentSelectedApplication;
- (void)previous;
- (void)next;
@property(readonly, nonatomic, getter=isVisible) _Bool visible;
- (void)dismiss;
- (void)activateWithKeyCommand:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

