//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBLayoutState.h"

#import "SBMainDisplayLayoutContext.h"

@class NSString, SBBreadcrumbState, SBLockStateAggregator, SBMainDisplaySceneManager, SBSideAppState, SpringBoard;

@interface SBMainDisplayLayoutState : SBLayoutState <SBMainDisplayLayoutContext>
{
    SBMainDisplaySceneManager *_sceneManager;
    SBLockStateAggregator *_lockStateAggregator;
    SpringBoard *_sbApp;
    SBSideAppState *_sideAppState;
    SBSideAppState *_externallyManagedSideAppState;
    SBBreadcrumbState *_breadcrumbState;
}

+ (long long)_defaultOrientation;
@property(readonly, retain, nonatomic) SBSideAppState *externallyManagedSideAppState; // @synthesize externallyManagedSideAppState=_externallyManagedSideAppState;
@property(readonly, retain, nonatomic) SBSideAppState *sideAppState; // @synthesize sideAppState=_sideAppState;
@property(readonly, retain, nonatomic) SBBreadcrumbState *breadcrumbState; // @synthesize breadcrumbState=_breadcrumbState;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (_Bool)includesStatusBarForLayoutRole:(long long)arg1;
- (long long)wallpaperModeForLayoutRole:(long long)arg1;
- (long long)wallpaperMode;
@property(readonly, nonatomic) long long externallyManagedSideAppWidth;
@property(readonly, nonatomic) long long externallyManagedSideAppPresentationStyle;
@property(readonly, nonatomic) long long sideAppWidth;
@property(readonly, nonatomic) long long sideAppPresentationStyle;
- (id)_layoutStateForTransitionContext:(id)arg1;
- (_Bool)isEqualToLayoutState:(id)arg1;
- (id)_stateWithElements:(id)arg1 andBreadcrumbState:(id)arg2 andSideAppState:(id)arg3 andExternallyManagedSideAppState:(id)arg4 interfaceOrientation:(long long)arg5;
- (void)dealloc;
- (id)_initWithElements:(id)arg1 andBreadcrumbState:(id)arg2 andSideAppState:(id)arg3 andExternallyManagedSideAppState:(id)arg4 interfaceOrientation:(long long)arg5 sceneManager:(id)arg6 applicationController:(id)arg7 lockStateAggregator:(id)arg8 sbApp:(id)arg9;
- (id)_initWithElements:(id)arg1 andBreadcrumbState:(id)arg2 andSideAppState:(id)arg3 andExternallyManagedSideAppState:(id)arg4 interfaceOrientation:(long long)arg5;
- (id)_initWithElements:(id)arg1;
- (id)transitionContextForResizingSideAppToWidth:(long long)arg1;
- (id)transitionContextForSettingSideAppPinned:(_Bool)arg1;
- (id)transitionContextForSuspendingPrimaryApp;
- (id)transitionContextForSuspendingSideApp;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) long long interfaceOrientation;
@property(readonly) Class superclass;

@end

