//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SBAppContainerViewController, SBAppResizingPlaceholderView, SBLayoutElementViewController, SBMainDisplaySceneLayoutResizeUIManager, UIView;

@protocol SBMainDisplaySceneLayoutResizeUIManagerDelegate <NSObject>
- (void)resizeUIManager:(SBMainDisplaySceneLayoutResizeUIManager *)arg1 willChangeDisplayModeOfAppController:(SBAppContainerViewController *)arg2 toDisplayMode:(long long)arg3;
- (void)resizeUIManager:(SBMainDisplaySceneLayoutResizeUIManager *)arg1 willChangeToState:(unsigned long long)arg2;
- (void)resizeUIManager:(SBMainDisplaySceneLayoutResizeUIManager *)arg1 didCreateResizingPlacholderView:(SBAppResizingPlaceholderView *)arg2 forLayoutElementViewController:(SBLayoutElementViewController *)arg3;
- (SBAppResizingPlaceholderView *)resizeUIManager:(SBMainDisplaySceneLayoutResizeUIManager *)arg1 cachedResizingPlaceholderViewForLayoutElementViewController:(SBLayoutElementViewController *)arg2;
- (void)resizeUIManager:(SBMainDisplaySceneLayoutResizeUIManager *)arg1 didCreateSceneSnapshotView:(UIView *)arg2 forLayoutElementViewController:(SBLayoutElementViewController *)arg3;
- (UIView *)resizeUIManager:(SBMainDisplaySceneLayoutResizeUIManager *)arg1 cachedSceneSnapshotViewForLayoutElementViewController:(SBLayoutElementViewController *)arg2;
@end

