//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBStatusBarStateProvider.h"

#import "UIStatusBarStateObserver.h"

@class NSString, SBSStatusBarStyleOverridesAssertion;

@interface SBMainStatusBarStateProvider : SBStatusBarStateProvider <UIStatusBarStateObserver>
{
    _Bool _overridePercent;
    _Bool _killActivity;
    _Bool _simulateInCallStatusBar;
    SBSStatusBarStyleOverridesAssertion *_inCallStatusBarStyleOverrideAssertion;
    _Bool _itemIsDisabled[27];
    _Bool _itemWasDisabled[27];
    _Bool _timeEnabled;
    _Bool _timeCloaked;
    _Bool _allButBatteryCloaked;
    _Bool _telephonyAndBluetoothCloaked;
}

+ (id)sharedInstance;
- (void)statusBarStateProvider:(id)arg1 didPostStatusBarData:(const CDStruct_7953f186 *)arg2 withActions:(int)arg3;
- (void)_toggleSimulatesInCallStatusBar;
- (void)_removeInCallStatusBarOverrideAssertion;
- (void)_composePostDataFromAggregatorData:(CDStruct_7953f186 *)arg1;
- (_Bool)_shouldPostForVisitedItem:(int)arg1 withUpdates:(_Bool)arg2 toAggregatorData:(const CDStruct_7953f186 *)arg3;
- (void)setTelephonyAndBluetoothItemsCloaked:(_Bool)arg1;
- (void)setAllItemsExceptBatteryCloaked:(_Bool)arg1;
- (void)setTimeCloaked:(_Bool)arg1;
- (void)enableTime:(_Bool)arg1 crossfade:(_Bool)arg2 crossfadeDuration:(double)arg3;
- (void)enableTime:(_Bool)arg1;
- (_Bool)isTimeEnabled;
- (void)_updateDisabledItems;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

