//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBApplication.h"

@interface SBNewsstandApplication : SBApplication
{
    unsigned int _supportsNewsstandContentBackgroundMode:1;
    unsigned long long _allowedContentNotificationsPerDay;
    unsigned char _newsstandWakes;
}

- (_Bool)supportsBackgroundAppRefresh;
- (_Bool)supportsNewsstandContentBackgroundMode;
- (_Bool)isNewsstandApplication;
- (_Bool)shouldThrottleContentNotificationOnDate:(id)arg1 withLastCount:(unsigned long long *)arg2 onDay:(long long *)arg3;
- (void)resumeForContentAvailable;
- (void)activate;
- (Class)iconClass;
- (id)initWithApplicationInfo:(id)arg1 bundle:(id)arg2 infoDictionary:(id)arg3 entitlements:(id)arg4 usesVisibiliyOverride:(_Bool)arg5;

@end

