//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBDosidoAnimator.h"

@interface SBReducedMotionDosidoAnimator : SBDosidoAnimator
{
}

- (void)_animateDosidoWithFactory:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_prepareDosido;

@end

