//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBTouchTemplatePinchGestureRecognizer.h"

@interface SBScrunchSystemGestureRecognizer : SBTouchTemplatePinchGestureRecognizer
{
}

- (double)animationDistance;
- (void)_log:(id)arg1;
- (void)_installTemplates;
- (id)initWithTarget:(id)arg1 action:(SEL)arg2;

@end

