//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIWindow.h"

#import "SBSceneResizeSnakebiteGestureDebugDelegate.h"

@class NSString, SBSceneResizeSnakebiteGestureRecognizer, UIView;

@interface SBSnakebiteDebugWindow : UIWindow <SBSceneResizeSnakebiteGestureDebugDelegate>
{
    UIView *_dividerView;
    UIView *_waitingTouchView;
    UIView *_otherFingerTouchableAreaView;
    UIView *_rightTouchableAreaView;
    SBSceneResizeSnakebiteGestureRecognizer *_snakebite;
}

@property(retain, nonatomic) SBSceneResizeSnakebiteGestureRecognizer *snakebite; // @synthesize snakebite=_snakebite;
- (void)debugDrawingUpdatedForSceneResizeGestureRecognizer:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 gesture:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

