//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface SBSpuriousScreenUndimmingAssertion : NSObject
{
    NSString *_identifier;
}

+ (id)debugDescription;
+ (_Bool)isAnyActive;
+ (void)_accessListWithBlock:(CDUnknownBlockType)arg1;
- (id)description;
- (void)dealloc;
- (id)initWithIdentifier:(id)arg1;

@end

