//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBSystemGestureManager.h"

@interface SBStarkSystemGestureManager : SBSystemGestureManager
{
}

- (_Bool)_shouldEnableSystemGestureWithType:(unsigned long long)arg1;
- (id)initWithDisplay:(id)arg1;

@end

