//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface SBSteppedAnimationTimingFunctionCalculator : NSObject
{
    NSMutableDictionary *_functionsByName;
    double _percentComplete;
}

@property(nonatomic) double percentComplete; // @synthesize percentComplete=_percentComplete;
- (double)valueForFunctionWithName:(id)arg1;
- (id)timingFunctionNames;
- (void)addTimingFunctionWithName:(id)arg1 fromNormalizedAnimationSettings:(id)arg2;
- (void)addTimingFunction:(id)arg1 withName:(id)arg2 constrainedToIntervalBetween:(double)arg3 and:(double)arg4;
- (void)dealloc;
- (id)init;

@end

