//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBUIMainScreenAnimationController.h"

#import "SBUIAnimationZoomUpDown.h"

@class BSAnimationSettings, FBWindowContextHostManager, NSString, SBAppStatusBarSettingsAssertion, SBAppStatusBarTransitionInfo, SBSceneLayoutAnimationWrapperView, UIView;

@interface SBUIAnimationZoomDownApp : SBUIMainScreenAnimationController <SBUIAnimationZoomUpDown>
{
    UIView *_viewToAnimate;
    SBAppStatusBarTransitionInfo *_appStatusBarTransitionInfo;
    BSAnimationSettings *_animationSettings;
    FBWindowContextHostManager *_deactivatingContextHostManager;
    SBSceneLayoutAnimationWrapperView *_wrapperView;
    SBAppStatusBarSettingsAssertion *_hideStatusBarAssertion;
    _Bool _zoomFullLayoutBounds;
}

@property(readonly) SBAppStatusBarTransitionInfo *appStatusBarTransitionInfo; // @synthesize appStatusBarTransitionInfo=_appStatusBarTransitionInfo;
@property(copy, nonatomic) BSAnimationSettings *animationSettings; // @synthesize animationSettings=_animationSettings;
- (void)setAnimatableWrapperView:(id)arg1;
- (double)_animationDelay;
- (double)_animationDuration;
- (void)_cleanupAnimation;
- (void)_startAnimation;
- (void)_prepareAnimation;
- (id)_viewsForAnimationStepping;
- (void)cleanupZoom;
- (void)animateZoomWithCompletion:(CDUnknownBlockType)arg1;
- (void)_animateWallpaperWithFactory:(id)arg1;
- (void)prepareZoom;
- (_Bool)prefersLayerHostSnapshot;
- (id)appStatusBarTransitionInfoWithStartEffectivelyHidden:(_Bool)arg1 endStyleRequest:(id)arg2 endOrientation:(long long)arg3;
- (id)deactivatingApp;
- (void)dealloc;
- (id)initWithTransitionContextProvider:(id)arg1 zoomFullLayoutBounds:(_Bool)arg2;
- (id)initWithTransitionContextProvider:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

