//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BSDescriptionProviding.h"
#import "NSCopying.h"
#import "SBActivationSettings.h"
#import "SBDeactivationSettings.h"
#import "SBLayoutElementProviding.h"

@class NSString, SBActivationSettings, SBDeactivationSettings;

@interface SBWorkspaceEntity : NSObject <NSCopying, SBActivationSettings, SBDeactivationSettings, BSDescriptionProviding, SBLayoutElementProviding>
{
    NSString *_identifier;
    long long _layoutRole;
    SBActivationSettings *_activationSettings;
    SBDeactivationSettings *_deactivationSettings;
    long long _mainDisplayPreferredInterfaceOrientation;
}

+ (id)entity;
@property(nonatomic, getter=_mainDisplayPreferredInterfaceOrientation, setter=_setMainDisplayPreferredInterfaceOrientation:) long long _mainDisplayPreferredInterfaceOrientation; // @synthesize _mainDisplayPreferredInterfaceOrientation;
@property(readonly, retain, nonatomic) SBDeactivationSettings *deactivationSettings; // @synthesize deactivationSettings=_deactivationSettings;
@property(readonly, retain, nonatomic) SBActivationSettings *activationSettings; // @synthesize activationSettings=_activationSettings;
@property(nonatomic) long long layoutRole; // @synthesize layoutRole=_layoutRole;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (id)layoutElementForRole:(long long)arg1;
- (id)layoutElement;
@property(readonly, copy, nonatomic) CDUnknownBlockType entityGenerator;
@property(readonly, nonatomic) Class viewControllerClass;
- (_Bool)hasLayoutAttributes:(unsigned long long)arg1;
- (_Bool)supportsLayoutRole:(long long)arg1;
@property(readonly, nonatomic) unsigned long long layoutAttributes;
@property(readonly, nonatomic) unsigned long long supportedLayoutRoles;
- (_Bool)hasSameIdentityAsElement:(id)arg1;
@property(readonly, copy, nonatomic) NSString *layoutIdentifier;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)succinctDescriptionBuilder;
- (id)succinctDescription;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (CDUnknownBlockType)_generator;
- (_Bool)_supportsDynamicResizing;
- (_Bool)_supportsPresentationAtAnySize;
- (_Bool)_supportsLayoutRole:(long long)arg1;
- (void)setPreferredInterfaceOrientation:(long long)arg1 onDisplay:(id)arg2;
- (long long)preferredInterfaceOrientationOnDisplay:(id)arg1;
- (_Bool)isAnalagousToEntity:(id)arg1;
@property(readonly, nonatomic) id <SBDisplay> representedDisplay;
@property(readonly, copy) NSString *description;
- (void)clearDeactivationSettings;
- (void)applyDeactivationSettings:(id)arg1;
- (id)copyDeactivationSettings;
- (id)objectForDeactivationSetting:(unsigned int)arg1;
- (void)setObject:(id)arg1 forDeactivationSetting:(unsigned int)arg2;
- (_Bool)boolForDeactivationSetting:(unsigned int)arg1;
- (long long)flagForDeactivationSetting:(unsigned int)arg1;
- (void)setFlag:(long long)arg1 forDeactivationSetting:(unsigned int)arg2;
- (void)clearActivationSettings;
- (void)applyActivationSettings:(id)arg1;
- (id)copyActivationSettings;
- (id)objectForActivationSetting:(unsigned int)arg1;
- (void)setObject:(id)arg1 forActivationSetting:(unsigned int)arg2;
- (_Bool)boolForActivationSetting:(unsigned int)arg1;
- (long long)flagForActivationSetting:(unsigned int)arg1;
- (void)setFlag:(long long)arg1 forActivationSetting:(unsigned int)arg2;
- (void)dealloc;
- (id)initWithDisplayChangeSettings:(id)arg1;
- (id)init;
- (_Bool)isAlertEntity;
- (_Bool)isSideSwitcherEntity;
- (_Bool)isHomeScreenEntity;
- (_Bool)isDeactivatingEntity;
- (_Bool)isPlaceholderEntity;
- (id)workspaceApplication;
- (_Bool)isApplicationEntity;
- (_Bool)isStarkNowPlayingEntity;
- (_Bool)isPrimarySwitcherEntity;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

