/*
* This header is generated by classdump-dyld 0.7
* on Sunday, November 22, 2015 at 10:28:31 PM Eastern Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libextension.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libextension.dylib/libextension.dylib-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>
#import <libobjc.A.dylib/NSSecureCoding.h>

@class NSMutableDictionary, AKAppleIDAuthenticationContext, NSAttributedString, NSArray, NSDictionary;

@interface NSExtensionItem : NSObject <NSCopying, NSSecureCoding> {

	NSMutableDictionary* _userInfo;

}

@property (setter=ak_setContext:,nonatomic,retain) AKAppleIDAuthenticationContext * ak_context; 
@property (nonatomic,copy) NSAttributedString * attributedTitle; 
@property (nonatomic,copy) NSAttributedString * attributedContentText; 
@property (nonatomic,copy) NSArray * attachments; 
@property (nonatomic,copy) NSDictionary * userInfo; 
+(id)extensionItemWithAppleIDAuthenticationContext:(id)arg1 ;
+(BOOL)supportsSecureCoding;
-(void)ak_setContext:(id)arg1 ;
-(AKAppleIDAuthenticationContext *)ak_context;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(void)dealloc;
-(id)init;
-(void)setAttributedTitle:(NSAttributedString *)arg1 ;
-(id)description;
-(void)setUserInfo:(NSDictionary *)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(NSDictionary *)userInfo;
-(NSAttributedString *)attributedTitle;
-(NSArray *)attachments;
-(void)setAttachments:(NSArray *)arg1 ;
-(void)setAttributedContentText:(NSAttributedString *)arg1 ;
-(id)_matchingDictionaryRepresentation;
-(NSAttributedString *)attributedContentText;
@end

