/*
* This header is generated by classdump-dyld 0.7
* on Sunday, November 22, 2015 at 10:28:29 PM Eastern Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libauthinstall.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libauthinstall.dylib/libauthinstall.dylib-Structs.h>
#import <libobjc.A.dylib/NSURLSessionDelegate.h>

@protocol OS_dispatch_queue;
@class NSObject, NSMutableDictionary, NSURLSession, NSString;

@interface AMAuthInstallURLSession : NSObject <NSURLSessionDelegate> {

	double _timeout;
	NSObject*<OS_dispatch_queue> _queue;
	NSMutableDictionary* _responses;
	NSMutableDictionary* _data;
	NSMutableDictionary* _completions;
	NSURLSession* _session;

}

@property (nonatomic,retain) NSObject*<OS_dispatch_queue> queue;              //@synthesize queue=_queue - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * responses;                 //@synthesize responses=_responses - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * data;                      //@synthesize data=_data - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * completions;               //@synthesize completions=_completions - In the implementation block
@property (nonatomic,retain) NSURLSession * session;                          //@synthesize session=_session - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)URLSession:(id)arg1 dataTask:(id)arg2 didReceiveResponse:(id)arg3 completionHandler:(/*^block*/id)arg4 ;
-(void)URLSession:(id)arg1 dataTask:(id)arg2 didReceiveData:(id)arg3 ;
-(void)URLSession:(id)arg1 task:(id)arg2 didCompleteWithError:(id)arg3 ;
-(void)URLSession:(id)arg1 didBecomeInvalidWithError:(id)arg2 ;
-(NSURLSession *)session;
-(NSObject*<OS_dispatch_queue>)queue;
-(void)setQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(void)dealloc;
-(NSMutableDictionary *)data;
-(void)setData:(NSMutableDictionary *)arg1 ;
-(void)setSession:(NSURLSession *)arg1 ;
-(id)initWithTimeout:(double)arg1 ;
-(NSMutableDictionary *)responses;
-(void)setResponses:(NSMutableDictionary *)arg1 ;
-(void)setCompletions:(NSMutableDictionary *)arg1 ;
-(NSMutableDictionary *)completions;
-(void)sendRequest:(CFHTTPMessageRef)arg1 completion:(/*^block*/id)arg2 ;
-(id)_defaultSessionConfigurationWithIdentifier:(id)arg1 ;
-(id)_defaultSession;
-(id)_urlRequestForHTTPMessage:(CFHTTPMessageRef)arg1 ;
@end

