/*
* This header is generated by classdump-dyld 0.7
* on Sunday, November 22, 2015 at 10:28:29 PM Eastern Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSDictionary;

@interface ACMBaseLocale : NSObject {

	NSDictionary* _localeStrings;
	ACMBaseLocale* _nextLocale;

}

@property (retain) ACMBaseLocale * nextLocale;              //@synthesize nextLocale=_nextLocale - In the implementation block
+(id)sharedInstance;
+(id)localizedString:(id)arg1 ;
+(id)currentLanguageCode;
+(void)initResources;
+(id)localeForIdentifier:(id)arg1 ;
+(id)localeForLanguage:(id)arg1 ;
-(void)dealloc;
-(id)objectForKey:(id)arg1 ;
-(void)setNextLocale:(ACMBaseLocale *)arg1 ;
-(ACMBaseLocale *)nextLocale;
@end

