/*
* This header is generated by classdump-dyld 0.7
* on Sunday, November 22, 2015 at 10:28:28 PM Eastern Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libacmobileshim.dylib/ACMBaseAuthenticationRequestImpl.h>
#import <libobjc.A.dylib/ACMExternalAuthenticationRequest.h>

@class NSString, NSNumber;

@interface ACMExternalAuthenticationRequestImpl : ACMBaseAuthenticationRequestImpl <ACMExternalAuthenticationRequest> {

	BOOL _useAlertView;
	BOOL _userNameFieldEditable;
	NSString* _alertViewPrompt;
	BOOL _automaticallyCancelWhenSwitchingToBackground;
	NSNumber* serverResponseTimeout;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (retain) NSString * realm; 
@property (retain) NSString * userName; 
@property (retain) NSNumber * appID; 
@property (retain) NSString * appIDKey; 
@property (retain) NSNumber * serverResponseTimeout; 
@property (assign) BOOL useAlertView;                                              //@synthesize useAlertView=_useAlertView - In the implementation block
@property (assign) BOOL userNameFieldEditable;                                     //@synthesize userNameFieldEditable=_userNameFieldEditable - In the implementation block
@property (retain) NSString * alertViewPrompt;                                     //@synthesize alertViewPrompt=_alertViewPrompt - In the implementation block
@property (assign) BOOL automaticallyCancelWhenSwitchingToBackground;              //@synthesize automaticallyCancelWhenSwitchingToBackground=_automaticallyCancelWhenSwitchingToBackground - In the implementation block
-(void)dealloc;
-(id)init;
-(BOOL)useAlertView;
-(NSNumber *)serverResponseTimeout;
-(BOOL)automaticallyCancelWhenSwitchingToBackground;
-(void)setUserNameFieldEditable:(BOOL)arg1 ;
-(void)setAlertViewPrompt:(NSString *)arg1 ;
-(void)setUseAlertView:(BOOL)arg1 ;
-(BOOL)userNameFieldEditable;
-(NSString *)alertViewPrompt;
-(void)setAutomaticallyCancelWhenSwitchingToBackground:(BOOL)arg1 ;
-(void)setServerResponseTimeout:(NSNumber *)arg1 ;
@end

