/*
* This header is generated by classdump-dyld 0.7
* on Sunday, November 22, 2015 at 10:28:28 PM Eastern Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libacmobileshim.dylib/ACMHTTPHandler.h>

@class ACMTicketVerificationRequestImpl;

@interface ACMHTTPTicketVerificationHandler : ACMHTTPHandler {

	ACMTicketVerificationRequestImpl* _request;

}

@property (retain) ACMTicketVerificationRequestImpl * request;              //@synthesize request=_request - In the implementation block
+(id)handlerWithRequest:(id)arg1 ;
-(void)dealloc;
-(ACMTicketVerificationRequestImpl *)request;
-(id)requestBody;
-(void)setRequest:(ACMTicketVerificationRequestImpl *)arg1 ;
@end

