/*
* This header is generated by classdump-dyld 0.7
* on Sunday, November 22, 2015 at 10:28:29 PM Eastern Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libacmobileshim.dylib/ACMLocale.h>

@interface ACMLocale_pl : ACMLocale
-(void)dealloc;
-(id)init;
@end

