/*
* This header is generated by classdump-dyld 0.7
* on Sunday, November 22, 2015 at 10:28:31 PM Eastern Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

typedef struct __CFString* CFStringRef;

typedef struct __CFDate* CFDateRef;

typedef struct _NSZone* NSZoneRef;

typedef struct {
	unsigned field1[8];
} SCD_Struct_RT3;

typedef struct sqlite3* sqlite3Ref;

typedef struct sqlite3_stmt* sqlite3_stmtRef;

typedef struct IONotificationPort* IONotificationPortRef;

typedef struct __WiFiNetwork* WiFiNetworkRef;

typedef struct __WiFiManagerClient* WiFiManagerClientRef;

typedef struct __WiFiDeviceClient* WiFiDeviceClientRef;

typedef struct __SCNetworkReachability* SCNetworkReachabilityRef;

typedef struct {
	double field1;
	double field2;
} SCD_Struct_RT11;

