/*
* This header is generated by classdump-dyld 0.7
* on Sunday, November 22, 2015 at 10:28:29 PM Eastern Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTNotifier.h>

@class NSDate, RTInvocationDispatcher, ASAssetQuery;

@interface RTAssetManager : RTNotifier {

	BOOL _ready;
	long long _currentReachability;
	NSDate* _dateOfLastUpdateAttempt;
	NSDate* _dateOfLastSuccessfulUpdate;
	RTInvocationDispatcher* _dispatcher;
	ASAssetQuery* _assetQuery;

}

@property (assign,nonatomic) long long currentReachability;                    //@synthesize currentReachability=_currentReachability - In the implementation block
@property (nonatomic,retain) NSDate * dateOfLastUpdateAttempt;                 //@synthesize dateOfLastUpdateAttempt=_dateOfLastUpdateAttempt - In the implementation block
@property (nonatomic,retain) NSDate * dateOfLastSuccessfulUpdate;              //@synthesize dateOfLastSuccessfulUpdate=_dateOfLastSuccessfulUpdate - In the implementation block
@property (nonatomic,retain) RTInvocationDispatcher * dispatcher;              //@synthesize dispatcher=_dispatcher - In the implementation block
@property (assign,nonatomic) BOOL ready;                                       //@synthesize ready=_ready - In the implementation block
@property (nonatomic,retain) ASAssetQuery * assetQuery;                        //@synthesize assetQuery=_assetQuery - In the implementation block
+(id)sharedInstance;
-(void)_unregisterForNotifications;
-(void)_registerForNotifications;
-(void)_setup;
-(id)init;
-(void)setReady:(BOOL)arg1 ;
-(BOOL)ready;
-(void)shutdown;
-(void)forceUpdateAssetMetadata;
-(RTInvocationDispatcher *)dispatcher;
-(void)setDispatcher:(RTInvocationDispatcher *)arg1 ;
-(void)setDateOfLastUpdateAttempt:(NSDate *)arg1 ;
-(void)setDateOfLastSuccessfulUpdate:(NSDate *)arg1 ;
-(void)_invalidateAssetQuery;
-(long long)currentReachability;
-(void)_finalizeAssetUpdateOperationWithError:(id)arg1 ;
-(void)performUpdateOfAssetsWithTypeAssetType:(id)arg1 handler:(/*^block*/id)arg2 ;
-(void)setCurrentReachability:(long long)arg1 ;
-(void)onReachabilityChange:(id)arg1 ;
-(ASAssetQuery *)assetQuery;
-(void)setAssetQuery:(ASAssetQuery *)arg1 ;
-(void)_performUpdateOfAssetsWithTypeAssetType:(id)arg1 handler:(/*^block*/id)arg2 ;
-(NSDate *)dateOfLastUpdateAttempt;
-(NSDate *)dateOfLastSuccessfulUpdate;
-(void)_downloadAsset:(id)arg1 handler:(/*^block*/id)arg2 ;
-(void)_installAsset:(id)arg1 handler:(/*^block*/id)arg2 ;
@end

