/*
* This header is generated by classdump-dyld 0.7
* on Sunday, November 22, 2015 at 10:28:30 PM Eastern Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libcoreroutine.dylib/libcoreroutine.dylib-Structs.h>
#import <libcoreroutine.dylib/RTNotifier.h>

@interface RTBatteryManager : RTNotifier {

	unsigned _battery;
	IONotificationPortRef _ioNotificationPort;
	unsigned _batteryInterestNotification;
	BOOL _monitorBatteryStatusChanges;
	long long _externalConnectedState;

}

@property (assign,nonatomic) BOOL monitorBatteryStatusChanges;              //@synthesize monitorBatteryStatusChanges=_monitorBatteryStatusChanges - In the implementation block
@property (assign,nonatomic) long long externalConnectedState;              //@synthesize externalConnectedState=_externalConnectedState - In the implementation block
+(id)sharedInstance;
+(id)externalConnectedStateToString:(long long)arg1 ;
-(void)dealloc;
-(id)init;
-(void)internalAddObserver:(id)arg1 name:(id)arg2 ;
-(void)internalRemoveObserver:(id)arg1 name:(id)arg2 ;
-(void)setMonitorBatteryStatusChanges:(BOOL)arg1 ;
-(void)startMonitoringBatteryStatusChanges;
-(void)stopMonitoringBatteryStatusChanges;
-(void)matchedBattery:(unsigned)arg1 ;
-(void)updateBatteryStatus:(unsigned)arg1 ;
-(long long)externalConnectedState;
-(void)setExternalConnectedState:(long long)arg1 ;
-(void)batteryStatusChange:(unsigned)arg1 messageType:(unsigned)arg2 messageArgument:(void*)arg3 ;
-(BOOL)monitorBatteryStatusChanges;
@end

