/*
* This header is generated by classdump-dyld 0.7
* on Sunday, November 22, 2015 at 10:28:31 PM Eastern Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol RTClientListenerProtocol <NSObject>
@required
-(void)handleDisconnectionForDaemonClient:(id)arg1;
-(void)saveDaemonClient:(id)arg1;
-(void)handleRestorationForDaemonClient:(id)arg1;

@end

