/*
* This header is generated by classdump-dyld 0.7
* on Sunday, November 22, 2015 at 10:28:31 PM Eastern Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTDataProviderDuet.h>
#import <libobjc.A.dylib/RTDataProviderProtocol.h>

@class NSString;

@interface RTDataProviderApplication : RTDataProviderDuet <RTDataProviderProtocol>

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)sharedInstance;
+(id)providerName;
-(id)init;
-(void)populateDataProviderWithHandler:(/*^block*/id)arg1 ;
-(id)supportedEventClasses;
@end

