/*
* This header is generated by classdump-dyld 0.7
* on Sunday, November 22, 2015 at 10:28:29 PM Eastern Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTNotifier.h>

@protocol OS_dispatch_queue;
@class NSMutableDictionary, NSObject;

@interface RTDefaultsManager : RTNotifier {

	NSMutableDictionary* _remoteDefaultsDictionary;
	NSObject*<OS_dispatch_queue> _serviceQueue;

}

@property (nonatomic,retain) NSMutableDictionary * remoteDefaultsDictionary;              //@synthesize remoteDefaultsDictionary=_remoteDefaultsDictionary - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_queue> serviceQueue;                   //@synthesize serviceQueue=_serviceQueue - In the implementation block
+(id)sharedInstance;
-(void)_unregisterForNotifications;
-(void)_registerForNotifications;
-(NSObject*<OS_dispatch_queue>)serviceQueue;
-(id)init;
-(id)objectForKey:(id)arg1 ;
-(void)setObject:(id)arg1 forKey:(id)arg2 ;
-(void)shutdown;
-(void)setRemoteDefaultsDictionary:(NSMutableDictionary *)arg1 ;
-(void)_loadRemoteDefaults;
-(void)onAssetDownloadNotification:(id)arg1 ;
-(NSMutableDictionary *)remoteDefaultsDictionary;
-(void)_installDefaults:(id)arg1 toDefaultsDictionary:(id)arg2 ;
-(void)_printCurrentEffectiveDefaults;
-(id)_objectForKey:(id)arg1 ;
-(void)handleAssetDownloadNotification:(id)arg1 ;
-(id)objectsForKeys:(id)arg1 ;
-(void)setObjects:(id)arg1 forKeys:(id)arg2 ;
-(void)setServiceQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
@end

