/*
* This header is generated by classdump-dyld 0.7
* on Sunday, November 22, 2015 at 10:28:30 PM Eastern Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class EKEventStore, NSObject;

@interface RTEventManager : NSObject {

	BOOL _accessToEventsGranted;
	EKEventStore* _eventStore;
	NSObject*<OS_dispatch_queue> _queue;

}

@property (nonatomic,retain) EKEventStore * eventStore;                       //@synthesize eventStore=_eventStore - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_queue> queue;              //@synthesize queue=_queue - In the implementation block
@property (assign,nonatomic) BOOL accessToEventsGranted;                      //@synthesize accessToEventsGranted=_accessToEventsGranted - In the implementation block
+(id)sharedInstance;
+(BOOL)reasonableDistanceBetweenEventLocation:(id)arg1 andLocation:(id)arg2 ;
-(EKEventStore *)eventStore;
-(void)setEventStore:(EKEventStore *)arg1 ;
-(void)fetchPredictedLocationsOfInterestOnDate:(id)arg1 withHandler:(/*^block*/id)arg2 ;
-(NSObject*<OS_dispatch_queue>)queue;
-(void)setQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(id)init;
-(void)setAccessToEventsGranted:(BOOL)arg1 ;
-(id)getEventsBetweenStartDate:(id)arg1 andEndDate:(id)arg2 ;
-(BOOL)accessToEventsGranted;
-(void)fetchNextPredictedLocationsOfInterestFromLocation:(id)arg1 startDate:(id)arg2 timeInterval:(double)arg3 withHandler:(/*^block*/id)arg4 ;
-(void)fetchPredictedLocationsOfInterestBetweenStartDate:(id)arg1 endDate:(id)arg2 withHandler:(/*^block*/id)arg3 ;
-(id)getEventsBetweenStartDate:(id)arg1 andEndDate:(id)arg2 calendars:(id)arg3 ;
-(id)getError;
-(id)getEventsSortedByStartDateBetweenStartDate:(id)arg1 andEndDate:(id)arg2 ;
-(id)getEventsSortedByEndDateBetweenStartDate:(id)arg1 andEndDate:(id)arg2 ;
-(void)_fetchLocationOfInterestForEvent:(id)arg1 withHandler:(/*^block*/id)arg2 ;
-(void)_fetchPredictedLocationsOfInterestBetweenStartDate:(id)arg1 endDate:(id)arg2 withHandler:(/*^block*/id)arg3 ;
-(void)_fetchPredictedLocationsOfInterestOnDate:(id)arg1 withHandler:(/*^block*/id)arg2 ;
-(void)_fetchPredictedLocationOfInterestAtEvent:(id)arg1 withHandler:(/*^block*/id)arg2 ;
-(void)fetchCurrentlyInEventWithHandler:(/*^block*/id)arg1 ;
-(void)fetchNextFreeStartDateWithHandler:(/*^block*/id)arg1 ;
-(void)fetchLastEventEndDateWithHandler:(/*^block*/id)arg1 ;
-(void)fetchEventsBetweenStartDate:(id)arg1 andEndDate:(id)arg2 withHandler:(/*^block*/id)arg3 ;
@end

