/*
* This header is generated by classdump-dyld 0.7
* on Sunday, November 22, 2015 at 10:28:29 PM Eastern Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class NSObject, NSMutableArray;

@interface RTInvocationDispatcher : NSObject {

	BOOL _valid;
	NSObject*<OS_dispatch_queue> _queue;
	NSMutableArray* _pendingInvocations;

}

@property (nonatomic,retain) NSObject*<OS_dispatch_queue> queue;               //@synthesize queue=_queue - In the implementation block
@property (nonatomic,retain) NSMutableArray * pendingInvocations;              //@synthesize pendingInvocations=_pendingInvocations - In the implementation block
@property (assign,nonatomic) BOOL valid;                                       //@synthesize valid=_valid - In the implementation block
-(NSObject*<OS_dispatch_queue>)queue;
-(void)setQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(id)init;
-(id)initWithQueue:(id)arg1 ;
-(BOOL)valid;
-(void)setValid:(BOOL)arg1 ;
-(void)shutdown;
-(BOOL)dispatchPendingInvocations;
-(NSMutableArray *)pendingInvocations;
-(void)removeAllPendingInvocations;
-(unsigned long long)countOfPendingInvocations;
-(id)addPendingInvocation:(id)arg1 failureBlock:(/*^block*/id)arg2 ;
-(void)removePendingInvocation:(id)arg1 ;
-(BOOL)invocationsPending;
-(void)setPendingInvocations:(NSMutableArray *)arg1 ;
@end

