/*
* This header is generated by classdump-dyld 0.7
* on Sunday, November 22, 2015 at 10:28:29 PM Eastern Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libobjc.A.dylib/RTDaemonInternalProtocol.h>

@protocol OS_dispatch_queue;
@class NSXPCConnection, NSObject, NSString;

@interface RTInternalDaemonClient : NSObject <RTDaemonInternalProtocol> {

	NSXPCConnection* _xpcConnection;
	NSObject*<OS_dispatch_queue> _queue;

}

@property (nonatomic,retain) NSXPCConnection * xpcConnection;                 //@synthesize xpcConnection=_xpcConnection - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_queue> queue;              //@synthesize queue=_queue - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(NSObject*<OS_dispatch_queue>)queue;
-(void)setQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(id)initWithQueue:(id)arg1 ;
-(NSXPCConnection *)xpcConnection;
-(void)setXpcConnection:(NSXPCConnection *)arg1 ;
-(void)forceSequentialClusterIdentification:(/*^block*/id)arg1 ;
-(void)injectLocationOfInterest:(id)arg1 reply:(/*^block*/id)arg2 ;
-(void)removeLocationOfInterest:(id)arg1 reply:(/*^block*/id)arg2 ;
-(void)injectVisit:(id)arg1 locationOfInterest:(id)arg2 reply:(/*^block*/id)arg3 ;
-(void)removeVisit:(id)arg1 locationOfInterest:(id)arg2 reply:(/*^block*/id)arg3 ;
-(void)fetchPredictedApplicationForEvent:(id)arg1 withReply:(/*^block*/id)arg2 ;
-(void)processDataForPredictionModelWithReply:(/*^block*/id)arg1 ;
-(void)printMagicalMomentsModelWithReply:(/*^block*/id)arg1 ;
-(void)forceUpdateAssetMetadata;
@end

