/*
* This header is generated by classdump-dyld 0.7
* on Sunday, November 22, 2015 at 10:28:30 PM Eastern Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTNotifier.h>

@protocol OS_dispatch_source;
@class CMMotionActivityManager, NSOperationQueue, RTMotionActivity, NSMutableArray, NSObject;

@interface RTMotionActivityManager : RTNotifier {

	BOOL _motionActivityAvailable;
	BOOL _dominantMotionActivityBootstrapped;
	CMMotionActivityManager* _motionActivityManager;
	NSOperationQueue* _operationQueue;
	long long _interestedInActivity;
	RTMotionActivity* _dominantMotionActivity;
	NSMutableArray* _motionActivities;
	NSObject*<OS_dispatch_source> _dominantMotionActivityTimer;
	unsigned long long _vehicleConnectedState;

}

@property (nonatomic,retain) CMMotionActivityManager * motionActivityManager;                        //@synthesize motionActivityManager=_motionActivityManager - In the implementation block
@property (assign,nonatomic) BOOL motionActivityAvailable;                                           //@synthesize motionActivityAvailable=_motionActivityAvailable - In the implementation block
@property (nonatomic,retain) NSOperationQueue * operationQueue;                                      //@synthesize operationQueue=_operationQueue - In the implementation block
@property (assign,nonatomic) long long interestedInActivity;                                         //@synthesize interestedInActivity=_interestedInActivity - In the implementation block
@property (nonatomic,retain) RTMotionActivity * dominantMotionActivity;                              //@synthesize dominantMotionActivity=_dominantMotionActivity - In the implementation block
@property (nonatomic,retain) NSMutableArray * motionActivities;                                      //@synthesize motionActivities=_motionActivities - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_source> dominantMotionActivityTimer;              //@synthesize dominantMotionActivityTimer=_dominantMotionActivityTimer - In the implementation block
@property (assign,nonatomic) BOOL dominantMotionActivityBootstrapped;                                //@synthesize dominantMotionActivityBootstrapped=_dominantMotionActivityBootstrapped - In the implementation block
@property (assign,nonatomic) unsigned long long vehicleConnectedState;                               //@synthesize vehicleConnectedState=_vehicleConnectedState - In the implementation block
+(id)sharedInstance;
+(id)motionActivityTypeToString:(unsigned long long)arg1 ;
+(id)motionActivityConfidenceToString:(unsigned long long)arg1 ;
+(void)removeActivites:(id)arg1 stoppedBeforeDate:(id)arg2 ;
+(id)buildHistogramForActivites:(id)arg1 betweenDate:(id)arg2 andDate:(id)arg3 ;
+(id)motionActivityVehicleConnectedStateToString:(unsigned long long)arg1 ;
-(void)dealloc;
-(id)init;
-(void)setOperationQueue:(NSOperationQueue *)arg1 ;
-(NSOperationQueue *)operationQueue;
-(void)internalAddObserver:(id)arg1 name:(id)arg2 ;
-(void)internalRemoveObserver:(id)arg1 name:(id)arg2 ;
-(unsigned long long)vehicleConnectedState;
-(void)_processDominantActivity;
-(NSMutableArray *)motionActivities;
-(void)setDominantMotionActivityBootstrapped:(BOOL)arg1 ;
-(BOOL)dominantMotionActivityBootstrapped;
-(void)setDominantMotionActivity:(RTMotionActivity *)arg1 ;
-(NSObject*<OS_dispatch_source>)dominantMotionActivityTimer;
-(RTMotionActivity *)dominantMotionActivity;
-(void)setVehicleConnectedState:(unsigned long long)arg1 ;
-(void)_onActivity:(id)arg1 ;
-(long long)interestedInActivity;
-(void)setInterestedInActivity:(long long)arg1 ;
-(void)_bootstrapDominantActivityWithMotionActivites:(id)arg1 ;
-(void)fetchMotionActivitiesFromStartDate:(id)arg1 toEndDate:(id)arg2 withHandler:(/*^block*/id)arg3 ;
-(void)onVehicleConnectedNotification;
-(void)onVehicleDisconnectedNotification;
-(CMMotionActivityManager *)motionActivityManager;
-(void)onActivity:(id)arg1 ;
-(BOOL)motionActivityAvailable;
-(void)_onVehicleConnectedNotification;
-(void)_onVehicleDisconnectedNotification;
-(void)setMotionActivityManager:(CMMotionActivityManager *)arg1 ;
-(void)setMotionActivityAvailable:(BOOL)arg1 ;
-(void)setMotionActivities:(NSMutableArray *)arg1 ;
-(void)setDominantMotionActivityTimer:(NSObject*<OS_dispatch_source>)arg1 ;
@end

