/*
* This header is generated by classdump-dyld 0.7
* on Sunday, November 22, 2015 at 10:28:29 PM Eastern Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class NSObject, NSMutableDictionary;

@interface RTNotifier : NSObject {

	NSObject*<OS_dispatch_queue> _queue;
	NSMutableDictionary* _observersMap;

}

@property (nonatomic,retain) NSObject*<OS_dispatch_queue> queue;              //@synthesize queue=_queue - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * observersMap;              //@synthesize observersMap=_observersMap - In the implementation block
-(NSObject*<OS_dispatch_queue>)queue;
-(void)setQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(id)init;
-(void)removeObserver:(id)arg1 ;
-(void)postNotification:(id)arg1 ;
-(id)initWithName:(id)arg1 ;
-(BOOL)observer:(id)arg1 observingNotificationName:(id)arg2 ;
-(void)addObserver:(id)arg1 selector:(SEL)arg2 name:(id)arg3 ;
-(void)removeObserver:(id)arg1 fromNotification:(id)arg2 ;
-(long long)getNumberOfObservers:(id)arg1 ;
-(void)internalAddObserver:(id)arg1 name:(id)arg2 ;
-(void)internalRemoveObserver:(id)arg1 name:(id)arg2 ;
-(void)postNotification:(id)arg1 toObserver:(id)arg2 ;
-(NSMutableDictionary *)observersMap;
-(void)removeAllObservers;
-(void)setObserversMap:(NSMutableDictionary *)arg1 ;
@end

