/*
* This header is generated by classdump-dyld 0.7
* on Sunday, November 22, 2015 at 10:28:31 PM Eastern Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol GEOMapItem;
@class RTPredictedLocationOfInterest, RTLOIDisplayInfo;

@interface RTPLOIETA : NSObject {

	RTPredictedLocationOfInterest* _ploi;
	id<GEOMapItem> _origin;
	unsigned _responseETASeconds;
	unsigned _baselineETASeconds;
	RTLOIDisplayInfo* _displayInfo;

}

@property (nonatomic,readonly) RTPredictedLocationOfInterest * ploi;              //@synthesize ploi=_ploi - In the implementation block
-(id)localizedMessage;
-(id)description;
-(id)localizedDescription;
-(id)localizedTitle;
-(id)mapsURL;
-(RTPredictedLocationOfInterest *)ploi;
-(BOOL)hasEquivalentDisplayTo:(id)arg1 ;
-(BOOL)etaExceedsMinimumETA:(unsigned)arg1 ;
-(id)displayInfo;
-(id)_preferredName;
-(id)_displayInfoForDate:(id)arg1 ;
-(id)initWithPLOI:(id)arg1 origin:(id)arg2 responseETASeconds:(unsigned)arg3 baselineETASeconds:(unsigned)arg4 ;
-(id)_urlName;
@end

