/*
* This header is generated by classdump-dyld 0.7
* on Sunday, November 22, 2015 at 10:28:29 PM Eastern Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTNotifier.h>

@class RTDataController;

@interface RTPredictedApplicationManager : RTNotifier {

	RTDataController* _appPredictionDataController;
	/*^block*/id _dataProcessingFinalizeBlock;

}

@property (nonatomic,retain) RTDataController * appPredictionDataController;              //@synthesize appPredictionDataController=_appPredictionDataController - In the implementation block
@property (nonatomic,copy) id dataProcessingFinalizeBlock;                                //@synthesize dataProcessingFinalizeBlock=_dataProcessingFinalizeBlock - In the implementation block
+(id)sharedInstance;
-(id)init;
-(void)shutdown;
-(void)onProtectedDataAvailabilityUpdate:(id)arg1 ;
-(id)dataProcessingFinalizeBlock;
-(void)processDataForPredictionModelWithHandler:(/*^block*/id)arg1 ;
-(RTDataController *)appPredictionDataController;
-(void)_stopMonitoringForPredictedApplications;
-(void)_startMonitoringForPredictedApplications;
-(void)printMagicalMomentsModel:(/*^block*/id)arg1 ;
-(void)internalAddObserver:(id)arg1 name:(id)arg2 ;
-(void)internalRemoveObserver:(id)arg1 name:(id)arg2 ;
-(void)fetchPredictedApplicationForEvent:(id)arg1 withHandler:(/*^block*/id)arg2 ;
-(void)setAppPredictionDataController:(RTDataController *)arg1 ;
-(void)setDataProcessingFinalizeBlock:(id)arg1 ;
@end

