/*
* This header is generated by classdump-dyld 0.7
* on Sunday, November 22, 2015 at 10:28:29 PM Eastern Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTNotification.h>

@class NSArray;

@interface RTPredictedApplicationNotification : RTNotification {

	NSArray* _predictedApplications;

}

@property (nonatomic,retain) NSArray * predictedApplications;              //@synthesize predictedApplications=_predictedApplications - In the implementation block
+(id)notificationName;
-(id)initWithPredictedApplications:(id)arg1 ;
-(NSArray *)predictedApplications;
-(void)setPredictedApplications:(NSArray *)arg1 ;
@end

