/*
* This header is generated by classdump-dyld 0.7
* on Sunday, November 22, 2015 at 10:28:30 PM Eastern Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libobjc.A.dylib/NSSecureCoding.h>

@protocol GEOMapItem;
@class RTStateModelLocation, NSMutableArray, NSDate;

@interface RTStateDepictionOneState : NSObject <NSSecureCoding> {

	RTStateModelLocation* _location;
	NSMutableArray* _histEntryExit_s;
	id<GEOMapItem> _mapItem;
	NSDate* _geocodeDate;
	long long _type;
	long long _source;

}

@property (nonatomic,retain) RTStateModelLocation * location;               //@synthesize location=_location - In the implementation block
@property (nonatomic,retain) NSMutableArray * histEntryExit_s;              //@synthesize histEntryExit_s=_histEntryExit_s - In the implementation block
@property (nonatomic,retain) id<GEOMapItem> mapItem;                        //@synthesize mapItem=_mapItem - In the implementation block
@property (nonatomic,retain) NSDate * geocodeDate;                          //@synthesize geocodeDate=_geocodeDate - In the implementation block
@property (assign,nonatomic) long long type;                                //@synthesize type=_type - In the implementation block
@property (assign,nonatomic) long long source;                              //@synthesize source=_source - In the implementation block
+(BOOL)supportsSecureCoding;
-(id<GEOMapItem>)mapItem;
-(void)setMapItem:(id<GEOMapItem>)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(id)init;
-(void)setType:(long long)arg1 ;
-(long long)type;
-(RTStateModelLocation *)location;
-(long long)source;
-(void)setSource:(long long)arg1 ;
-(void)setLocation:(RTStateModelLocation *)arg1 ;
-(NSMutableArray *)histEntryExit_s;
-(NSDate *)geocodeDate;
-(void)setHistEntryExit_s:(NSMutableArray *)arg1 ;
-(void)setGeocodeDate:(NSDate *)arg1 ;
@end

