/*
* This header is generated by classdump-dyld 0.7
* on Sunday, November 22, 2015 at 10:28:30 PM Eastern Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libobjc.A.dylib/NSSecureCoding.h>

@interface RTStateTransitionOneTimeTrans : NSObject <NSSecureCoding> {

	double _start_s;
	double _stop_s;
	unsigned long long _motionActivityType;

}

@property (assign,nonatomic) double start_s;                                     //@synthesize start_s=_start_s - In the implementation block
@property (assign,nonatomic) double stop_s;                                      //@synthesize stop_s=_stop_s - In the implementation block
@property (assign,nonatomic) unsigned long long motionActivityType;              //@synthesize motionActivityType=_motionActivityType - In the implementation block
+(BOOL)supportsSecureCoding;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(id)initWithStart:(double)arg1 stop:(double)arg2 motionActivityType:(unsigned long long)arg3 ;
-(double)start_s;
-(void)setStart_s:(double)arg1 ;
-(double)stop_s;
-(void)setStop_s:(double)arg1 ;
-(unsigned long long)motionActivityType;
-(void)setMotionActivityType:(unsigned long long)arg1 ;
@end

