/*
* This header is generated by classdump-dyld 0.7
* on Sunday, November 22, 2015 at 10:28:31 PM Eastern Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class NSObject, RTPLOIETA, NSDate, RTPersistentTimer;

@interface RTTrafficConditionsManager : NSObject {

	NSObject*<OS_dispatch_queue> _queue;
	unsigned long long _vehicleConnectedState;
	RTPLOIETA* _ploiEta;
	NSDate* _showTrafficConditionsDate;
	RTPersistentTimer* _showTrafficConditionsTimer;

}

@property (nonatomic,retain) NSObject*<OS_dispatch_queue> queue;                          //@synthesize queue=_queue - In the implementation block
@property (assign,nonatomic) unsigned long long vehicleConnectedState;                    //@synthesize vehicleConnectedState=_vehicleConnectedState - In the implementation block
@property (nonatomic,retain) RTPLOIETA * ploiEta;                                         //@synthesize ploiEta=_ploiEta - In the implementation block
@property (nonatomic,retain) NSDate * showTrafficConditionsDate;                          //@synthesize showTrafficConditionsDate=_showTrafficConditionsDate - In the implementation block
@property (nonatomic,retain) RTPersistentTimer * showTrafficConditionsTimer;              //@synthesize showTrafficConditionsTimer=_showTrafficConditionsTimer - In the implementation block
+(id)sharedInstance;
+(void)fetchPLOIETAWithHandler:(/*^block*/id)arg1 ;
+(void)fetchPLOIETAFrom:(id)arg1 to:(id)arg2 withHandler:(/*^block*/id)arg3 ;
+(BOOL)mapsAuthorized;
-(void)_setup;
-(NSObject*<OS_dispatch_queue>)queue;
-(void)setQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(void)dealloc;
-(id)init;
-(unsigned long long)vehicleConnectedState;
-(void)setVehicleConnectedState:(unsigned long long)arg1 ;
-(RTPLOIETA *)ploiEta;
-(void)setPloiEta:(RTPLOIETA *)arg1 ;
-(RTPersistentTimer *)showTrafficConditionsTimer;
-(void)setShowTrafficConditionsTimer:(RTPersistentTimer *)arg1 ;
-(NSDate *)showTrafficConditionsDate;
-(void)_clearTrafficConditions;
-(void)setShowTrafficConditionsTimer;
-(void)onMotionActivityNotification:(id)arg1 ;
-(void)_showTrafficConditions;
-(void)_updateTrafficCondtions;
-(void)_onMotionActivityNotification:(id)arg1 ;
-(void)setShowTrafficConditionsDate:(NSDate *)arg1 ;
@end

