/*
* This header is generated by classdump-dyld 0.7
* on Sunday, November 22, 2015 at 10:28:30 PM Eastern Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTNotification.h>

@class NSString, NSDictionary;

@interface RTWalletManagerNotificationPassUsed : RTNotification {

	NSString* _identifier;
	long long _source;
	NSDictionary* _infoDict;

}

@property (nonatomic,readonly) NSString * identifier;              //@synthesize identifier=_identifier - In the implementation block
@property (nonatomic,readonly) long long source;                   //@synthesize source=_source - In the implementation block
@property (nonatomic,retain) NSDictionary * infoDict;              //@synthesize infoDict=_infoDict - In the implementation block
+(id)notificationName;
-(id)init;
-(NSString *)identifier;
-(long long)source;
-(id)initWithIdentifier:(id)arg1 source:(long long)arg2 info:(id)arg3 ;
-(NSDictionary *)infoDict;
-(void)setInfoDict:(NSDictionary *)arg1 ;
@end

