/*
* This header is generated by classdump-dyld 0.7
* on Sunday, November 22, 2015 at 10:28:23 PM Eastern Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libAWDSupportFramework.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libAWDSupportFramework.dylib/libAWDSupportFramework.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString;

@interface AWDAirPlayAudioSessionEndedOnClient : PBCodable <NSCopying> {

	unsigned long long _timestamp;
	unsigned _duration;
	unsigned _futileRetransmits;
	int _reason;
	unsigned _retransmits;
	NSString* _sessionUUID;
	unsigned _slowKeepAlives;
	SCD_Struct_AW1 _has;

}

@property (nonatomic,readonly) BOOL hasSessionUUID; 
@property (nonatomic,retain) NSString * sessionUUID;                    //@synthesize sessionUUID=_sessionUUID - In the implementation block
@property (assign,nonatomic) BOOL hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;              //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) BOOL hasReason; 
@property (assign,nonatomic) int reason;                                //@synthesize reason=_reason - In the implementation block
@property (assign,nonatomic) BOOL hasDuration; 
@property (assign,nonatomic) unsigned duration;                         //@synthesize duration=_duration - In the implementation block
@property (assign,nonatomic) BOOL hasSlowKeepAlives; 
@property (assign,nonatomic) unsigned slowKeepAlives;                   //@synthesize slowKeepAlives=_slowKeepAlives - In the implementation block
@property (assign,nonatomic) BOOL hasRetransmits; 
@property (assign,nonatomic) unsigned retransmits;                      //@synthesize retransmits=_retransmits - In the implementation block
@property (assign,nonatomic) BOOL hasFutileRetransmits; 
@property (assign,nonatomic) unsigned futileRetransmits;                //@synthesize futileRetransmits=_futileRetransmits - In the implementation block
-(void)setReason:(int)arg1 ;
-(void)dealloc;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(unsigned long long)timestamp;
-(unsigned)duration;
-(void)setDuration:(unsigned)arg1 ;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)dictionaryRepresentation;
-(int)reason;
-(void)mergeFrom:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(BOOL)hasTimestamp;
-(void)setHasTimestamp:(BOOL)arg1 ;
-(BOOL)hasDuration;
-(void)setHasDuration:(BOOL)arg1 ;
-(BOOL)readFrom:(id)arg1 ;
-(void)setSessionUUID:(NSString *)arg1 ;
-(BOOL)hasSessionUUID;
-(void)setHasReason:(BOOL)arg1 ;
-(BOOL)hasReason;
-(void)setSlowKeepAlives:(unsigned)arg1 ;
-(void)setHasSlowKeepAlives:(BOOL)arg1 ;
-(BOOL)hasSlowKeepAlives;
-(void)setRetransmits:(unsigned)arg1 ;
-(void)setHasRetransmits:(BOOL)arg1 ;
-(BOOL)hasRetransmits;
-(void)setFutileRetransmits:(unsigned)arg1 ;
-(void)setHasFutileRetransmits:(BOOL)arg1 ;
-(BOOL)hasFutileRetransmits;
-(NSString *)sessionUUID;
-(unsigned)slowKeepAlives;
-(unsigned)retransmits;
-(unsigned)futileRetransmits;
@end

