/*
* This header is generated by classdump-dyld 0.7
* on Sunday, November 22, 2015 at 10:28:24 PM Eastern Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libAWDSupportFramework.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libAWDSupportFramework.dylib/libAWDSupportFramework.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@interface AWDCoreRoutineModelLearnedNonGeocodeableEvents : PBCodable <NSCopying> {

	unsigned long long _timestamp;
	int _learnedNongeocodableEvents;
	int _nongeocodableEvents;
	int _unlearnedNongeocodableEvents;
	SCD_Struct_AW10 _has;

}

@property (assign,nonatomic) BOOL hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;                      //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) BOOL hasUnlearnedNongeocodableEvents; 
@property (assign,nonatomic) int unlearnedNongeocodableEvents;                  //@synthesize unlearnedNongeocodableEvents=_unlearnedNongeocodableEvents - In the implementation block
@property (assign,nonatomic) BOOL hasLearnedNongeocodableEvents; 
@property (assign,nonatomic) int learnedNongeocodableEvents;                    //@synthesize learnedNongeocodableEvents=_learnedNongeocodableEvents - In the implementation block
@property (assign,nonatomic) BOOL hasNongeocodableEvents; 
@property (assign,nonatomic) int nongeocodableEvents;                           //@synthesize nongeocodableEvents=_nongeocodableEvents - In the implementation block
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(unsigned long long)timestamp;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)dictionaryRepresentation;
-(void)mergeFrom:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(BOOL)hasTimestamp;
-(void)setHasTimestamp:(BOOL)arg1 ;
-(BOOL)readFrom:(id)arg1 ;
-(void)setUnlearnedNongeocodableEvents:(int)arg1 ;
-(void)setHasUnlearnedNongeocodableEvents:(BOOL)arg1 ;
-(BOOL)hasUnlearnedNongeocodableEvents;
-(void)setLearnedNongeocodableEvents:(int)arg1 ;
-(void)setHasLearnedNongeocodableEvents:(BOOL)arg1 ;
-(BOOL)hasLearnedNongeocodableEvents;
-(void)setNongeocodableEvents:(int)arg1 ;
-(void)setHasNongeocodableEvents:(BOOL)arg1 ;
-(BOOL)hasNongeocodableEvents;
-(int)unlearnedNongeocodableEvents;
-(int)learnedNongeocodableEvents;
-(int)nongeocodableEvents;
@end

