/*
* This header is generated by classdump-dyld 0.7
* on Sunday, November 22, 2015 at 10:28:24 PM Eastern Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libAWDSupportFramework.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libAWDSupportFramework.dylib/libAWDSupportFramework.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@interface AWDHealthKitActivityRingEvent : PBCodable <NSCopying> {

	unsigned long long _eventTimestamp;
	unsigned long long _timestamp;
	unsigned _activeSeconds;
	unsigned _age;
	unsigned _biologicalSex;
	unsigned _briskMinutes;
	unsigned _energyBurned;
	unsigned _energyBurnedGoal;
	unsigned _height;
	unsigned _weight;
	SCD_Struct_AW9 _has;

}

@property (assign,nonatomic) BOOL hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;                   //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) BOOL hasEnergyBurned; 
@property (assign,nonatomic) unsigned energyBurned;                          //@synthesize energyBurned=_energyBurned - In the implementation block
@property (assign,nonatomic) BOOL hasBriskMinutes; 
@property (assign,nonatomic) unsigned briskMinutes;                          //@synthesize briskMinutes=_briskMinutes - In the implementation block
@property (assign,nonatomic) BOOL hasActiveSeconds; 
@property (assign,nonatomic) unsigned activeSeconds;                         //@synthesize activeSeconds=_activeSeconds - In the implementation block
@property (assign,nonatomic) BOOL hasEnergyBurnedGoal; 
@property (assign,nonatomic) unsigned energyBurnedGoal;                      //@synthesize energyBurnedGoal=_energyBurnedGoal - In the implementation block
@property (assign,nonatomic) BOOL hasEventTimestamp; 
@property (assign,nonatomic) unsigned long long eventTimestamp;              //@synthesize eventTimestamp=_eventTimestamp - In the implementation block
@property (assign,nonatomic) BOOL hasBiologicalSex; 
@property (assign,nonatomic) unsigned biologicalSex;                         //@synthesize biologicalSex=_biologicalSex - In the implementation block
@property (assign,nonatomic) BOOL hasHeight; 
@property (assign,nonatomic) unsigned height;                                //@synthesize height=_height - In the implementation block
@property (assign,nonatomic) BOOL hasWeight; 
@property (assign,nonatomic) unsigned weight;                                //@synthesize weight=_weight - In the implementation block
@property (assign,nonatomic) BOOL hasAge; 
@property (assign,nonatomic) unsigned age;                                   //@synthesize age=_age - In the implementation block
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(unsigned long long)timestamp;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(unsigned)height;
-(id)dictionaryRepresentation;
-(void)setHeight:(unsigned)arg1 ;
-(unsigned)weight;
-(void)setWeight:(unsigned)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(BOOL)hasHeight;
-(void)setHasHeight:(BOOL)arg1 ;
-(BOOL)hasTimestamp;
-(void)setHasTimestamp:(BOOL)arg1 ;
-(unsigned long long)eventTimestamp;
-(void)setHasEventTimestamp:(BOOL)arg1 ;
-(BOOL)hasEventTimestamp;
-(void)setEventTimestamp:(unsigned long long)arg1 ;
-(BOOL)readFrom:(id)arg1 ;
-(void)setEnergyBurned:(unsigned)arg1 ;
-(void)setHasEnergyBurned:(BOOL)arg1 ;
-(BOOL)hasEnergyBurned;
-(void)setBriskMinutes:(unsigned)arg1 ;
-(void)setHasBriskMinutes:(BOOL)arg1 ;
-(BOOL)hasBriskMinutes;
-(void)setActiveSeconds:(unsigned)arg1 ;
-(void)setHasActiveSeconds:(BOOL)arg1 ;
-(BOOL)hasActiveSeconds;
-(void)setEnergyBurnedGoal:(unsigned)arg1 ;
-(void)setHasEnergyBurnedGoal:(BOOL)arg1 ;
-(BOOL)hasEnergyBurnedGoal;
-(void)setBiologicalSex:(unsigned)arg1 ;
-(void)setHasBiologicalSex:(BOOL)arg1 ;
-(BOOL)hasBiologicalSex;
-(void)setHasWeight:(BOOL)arg1 ;
-(BOOL)hasWeight;
-(void)setAge:(unsigned)arg1 ;
-(void)setHasAge:(BOOL)arg1 ;
-(BOOL)hasAge;
-(unsigned)energyBurned;
-(unsigned)briskMinutes;
-(unsigned)activeSeconds;
-(unsigned)energyBurnedGoal;
-(unsigned)biologicalSex;
-(unsigned)age;
@end

