/*
* This header is generated by classdump-dyld 0.7
* on Sunday, November 22, 2015 at 10:28:24 PM Eastern Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libAWDSupportFramework.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libAWDSupportFramework.dylib/libAWDSupportFramework.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@interface AWDHomeKitConfiguration : PBCodable <NSCopying> {

	unsigned long long _timestamp;
	unsigned _databaseSize;
	unsigned _numAccessories;
	unsigned _numAccessoryServiceGroups;
	unsigned _numHomes;
	unsigned _numRooms;
	unsigned _numScenes;
	unsigned _numServices;
	unsigned _numTriggers;
	unsigned _numUsers;
	unsigned _numZones;
	SCD_Struct_AW12 _has;

}

@property (assign,nonatomic) BOOL hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;                    //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) BOOL hasNumHomes; 
@property (assign,nonatomic) unsigned numHomes;                               //@synthesize numHomes=_numHomes - In the implementation block
@property (assign,nonatomic) BOOL hasNumAccessories; 
@property (assign,nonatomic) unsigned numAccessories;                         //@synthesize numAccessories=_numAccessories - In the implementation block
@property (assign,nonatomic) BOOL hasNumServices; 
@property (assign,nonatomic) unsigned numServices;                            //@synthesize numServices=_numServices - In the implementation block
@property (assign,nonatomic) BOOL hasNumUsers; 
@property (assign,nonatomic) unsigned numUsers;                               //@synthesize numUsers=_numUsers - In the implementation block
@property (assign,nonatomic) BOOL hasNumScenes; 
@property (assign,nonatomic) unsigned numScenes;                              //@synthesize numScenes=_numScenes - In the implementation block
@property (assign,nonatomic) BOOL hasNumTriggers; 
@property (assign,nonatomic) unsigned numTriggers;                            //@synthesize numTriggers=_numTriggers - In the implementation block
@property (assign,nonatomic) BOOL hasNumAccessoryServiceGroups; 
@property (assign,nonatomic) unsigned numAccessoryServiceGroups;              //@synthesize numAccessoryServiceGroups=_numAccessoryServiceGroups - In the implementation block
@property (assign,nonatomic) BOOL hasDatabaseSize; 
@property (assign,nonatomic) unsigned databaseSize;                           //@synthesize databaseSize=_databaseSize - In the implementation block
@property (assign,nonatomic) BOOL hasNumRooms; 
@property (assign,nonatomic) unsigned numRooms;                               //@synthesize numRooms=_numRooms - In the implementation block
@property (assign,nonatomic) BOOL hasNumZones; 
@property (assign,nonatomic) unsigned numZones;                               //@synthesize numZones=_numZones - In the implementation block
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(unsigned long long)timestamp;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)dictionaryRepresentation;
-(void)mergeFrom:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(unsigned)databaseSize;
-(BOOL)hasTimestamp;
-(void)setHasTimestamp:(BOOL)arg1 ;
-(BOOL)readFrom:(id)arg1 ;
-(void)setNumHomes:(unsigned)arg1 ;
-(void)setHasNumHomes:(BOOL)arg1 ;
-(BOOL)hasNumHomes;
-(void)setNumAccessories:(unsigned)arg1 ;
-(void)setHasNumAccessories:(BOOL)arg1 ;
-(BOOL)hasNumAccessories;
-(void)setNumServices:(unsigned)arg1 ;
-(void)setHasNumServices:(BOOL)arg1 ;
-(BOOL)hasNumServices;
-(void)setNumUsers:(unsigned)arg1 ;
-(void)setHasNumUsers:(BOOL)arg1 ;
-(BOOL)hasNumUsers;
-(void)setNumScenes:(unsigned)arg1 ;
-(void)setHasNumScenes:(BOOL)arg1 ;
-(BOOL)hasNumScenes;
-(void)setNumTriggers:(unsigned)arg1 ;
-(void)setHasNumTriggers:(BOOL)arg1 ;
-(BOOL)hasNumTriggers;
-(void)setNumAccessoryServiceGroups:(unsigned)arg1 ;
-(void)setHasNumAccessoryServiceGroups:(BOOL)arg1 ;
-(BOOL)hasNumAccessoryServiceGroups;
-(void)setDatabaseSize:(unsigned)arg1 ;
-(void)setHasDatabaseSize:(BOOL)arg1 ;
-(BOOL)hasDatabaseSize;
-(void)setNumRooms:(unsigned)arg1 ;
-(void)setHasNumRooms:(BOOL)arg1 ;
-(BOOL)hasNumRooms;
-(void)setNumZones:(unsigned)arg1 ;
-(void)setHasNumZones:(BOOL)arg1 ;
-(BOOL)hasNumZones;
-(unsigned)numHomes;
-(unsigned)numAccessories;
-(unsigned)numServices;
-(unsigned)numUsers;
-(unsigned)numScenes;
-(unsigned)numTriggers;
-(unsigned)numAccessoryServiceGroups;
-(unsigned)numRooms;
-(unsigned)numZones;
@end

