/*
* This header is generated by classdump-dyld 0.7
* on Sunday, November 22, 2015 at 10:28:25 PM Eastern Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libAWDSupportFramework.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libAWDSupportFramework.dylib/libAWDSupportFramework.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString;

@interface AWDIMessageDowngrade : PBCodable <NSCopying> {

	unsigned long long _timestamp;
	unsigned _durationBeforeDowngrade;
	NSString* _guid;
	unsigned _isManualDowngrade;
	SCD_Struct_AW6 _has;

}

@property (nonatomic,readonly) BOOL hasGuid; 
@property (nonatomic,retain) NSString * guid;                               //@synthesize guid=_guid - In the implementation block
@property (assign,nonatomic) BOOL hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;                  //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) BOOL hasDurationBeforeDowngrade; 
@property (assign,nonatomic) unsigned durationBeforeDowngrade;              //@synthesize durationBeforeDowngrade=_durationBeforeDowngrade - In the implementation block
@property (assign,nonatomic) BOOL hasIsManualDowngrade; 
@property (assign,nonatomic) unsigned isManualDowngrade;                    //@synthesize isManualDowngrade=_isManualDowngrade - In the implementation block
-(void)dealloc;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(unsigned long long)timestamp;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)dictionaryRepresentation;
-(void)mergeFrom:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(BOOL)hasTimestamp;
-(void)setHasTimestamp:(BOOL)arg1 ;
-(BOOL)hasGuid;
-(NSString *)guid;
-(void)setGuid:(NSString *)arg1 ;
-(BOOL)readFrom:(id)arg1 ;
-(void)setDurationBeforeDowngrade:(unsigned)arg1 ;
-(void)setHasDurationBeforeDowngrade:(BOOL)arg1 ;
-(BOOL)hasDurationBeforeDowngrade;
-(void)setIsManualDowngrade:(unsigned)arg1 ;
-(void)setHasIsManualDowngrade:(BOOL)arg1 ;
-(BOOL)hasIsManualDowngrade;
-(unsigned)durationBeforeDowngrade;
-(unsigned)isManualDowngrade;
@end

