/*
* This header is generated by classdump-dyld 0.7
* on Sunday, November 22, 2015 at 10:28:25 PM Eastern Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libAWDSupportFramework.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libAWDSupportFramework.dylib/libAWDSupportFramework.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSMutableArray;

@interface AWDLibnetcoreCellularFallbackReport : PBCodable <NSCopying> {

	SCD_Struct_AW25* _networkEvents;
	SCD_Struct_AW26* _timeToNetworkEventsMsecs;
	unsigned long long _fallbackTimerMsecs;
	NSMutableArray* _dataUsageSnapshotsAtNetworkEvents;
	int _denyReason;
	NSMutableArray* _primaryInterfaceAttemptStatisticsReports;
	BOOL _fellback;
	SCD_Struct_AW6 _has;

}

@property (assign,nonatomic) BOOL hasFellback; 
@property (assign,nonatomic) BOOL fellback;                                                          //@synthesize fellback=_fellback - In the implementation block
@property (assign,nonatomic) BOOL hasDenyReason; 
@property (assign,nonatomic) int denyReason;                                                         //@synthesize denyReason=_denyReason - In the implementation block
@property (assign,nonatomic) BOOL hasFallbackTimerMsecs; 
@property (assign,nonatomic) unsigned long long fallbackTimerMsecs;                                  //@synthesize fallbackTimerMsecs=_fallbackTimerMsecs - In the implementation block
@property (nonatomic,readonly) unsigned long long networkEventsCount; 
@property (nonatomic,readonly) int* networkEvents; 
@property (nonatomic,readonly) unsigned long long timeToNetworkEventsMsecsCount; 
@property (nonatomic,readonly) unsigned long long* timeToNetworkEventsMsecs; 
@property (nonatomic,retain) NSMutableArray * primaryInterfaceAttemptStatisticsReports;              //@synthesize primaryInterfaceAttemptStatisticsReports=_primaryInterfaceAttemptStatisticsReports - In the implementation block
@property (nonatomic,retain) NSMutableArray * dataUsageSnapshotsAtNetworkEvents;                     //@synthesize dataUsageSnapshotsAtNetworkEvents=_dataUsageSnapshotsAtNetworkEvents - In the implementation block
-(void)dealloc;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)dictionaryRepresentation;
-(void)mergeFrom:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(BOOL)readFrom:(id)arg1 ;
-(void)setPrimaryInterfaceAttemptStatisticsReports:(NSMutableArray *)arg1 ;
-(void)setDataUsageSnapshotsAtNetworkEvents:(NSMutableArray *)arg1 ;
-(void)addPrimaryInterfaceAttemptStatisticsReports:(id)arg1 ;
-(void)addDataUsageSnapshotsAtNetworkEvents:(id)arg1 ;
-(unsigned long long)networkEventsCount;
-(void)clearNetworkEvents;
-(int)networkEventsAtIndex:(unsigned long long)arg1 ;
-(void)addNetworkEvents:(int)arg1 ;
-(unsigned long long)timeToNetworkEventsMsecsCount;
-(void)clearTimeToNetworkEventsMsecs;
-(unsigned long long)timeToNetworkEventsMsecsAtIndex:(unsigned long long)arg1 ;
-(void)addTimeToNetworkEventsMsecs:(unsigned long long)arg1 ;
-(unsigned long long)primaryInterfaceAttemptStatisticsReportsCount;
-(void)clearPrimaryInterfaceAttemptStatisticsReports;
-(id)primaryInterfaceAttemptStatisticsReportsAtIndex:(unsigned long long)arg1 ;
-(unsigned long long)dataUsageSnapshotsAtNetworkEventsCount;
-(void)clearDataUsageSnapshotsAtNetworkEvents;
-(id)dataUsageSnapshotsAtNetworkEventsAtIndex:(unsigned long long)arg1 ;
-(void)setFellback:(BOOL)arg1 ;
-(void)setHasFellback:(BOOL)arg1 ;
-(BOOL)hasFellback;
-(int)denyReason;
-(void)setDenyReason:(int)arg1 ;
-(void)setHasDenyReason:(BOOL)arg1 ;
-(BOOL)hasDenyReason;
-(void)setFallbackTimerMsecs:(unsigned long long)arg1 ;
-(void)setHasFallbackTimerMsecs:(BOOL)arg1 ;
-(BOOL)hasFallbackTimerMsecs;
-(int*)networkEvents;
-(void)setNetworkEvents:(int*)arg1 count:(unsigned long long)arg2 ;
-(unsigned long long*)timeToNetworkEventsMsecs;
-(void)setTimeToNetworkEventsMsecs:(unsigned long long*)arg1 count:(unsigned long long)arg2 ;
-(BOOL)fellback;
-(unsigned long long)fallbackTimerMsecs;
-(NSMutableArray *)primaryInterfaceAttemptStatisticsReports;
-(NSMutableArray *)dataUsageSnapshotsAtNetworkEvents;
@end

