/*
* This header is generated by classdump-dyld 0.7
* on Sunday, November 22, 2015 at 10:28:25 PM Eastern Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libAWDSupportFramework.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libAWDSupportFramework.dylib/libAWDSupportFramework.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSMutableArray, NSString;

@interface AWDMMCSPutRequestInfo : PBCodable <NSCopying> {

	long long _duration;
	long long _startTime;
	long long _timestamp;
	NSMutableArray* _authHttpInfos;
	NSMutableArray* _cancelErrors;
	int _cancelledErrorCode;
	NSString* _cancelledErrorDomain;
	NSMutableArray* _chunkingInfos;
	int _chunksUploaded;
	NSString* _clientId;
	NSMutableArray* _completeHttpInfos;
	NSMutableArray* _containerHttpInfos;
	NSMutableArray* _errors;
	int _itemCount;
	int _itemsAlreadyPresentCount;
	int _itemsNotPresentCount;
	int _itemsPartiallyPresentCount;
	int _requestErrorCode;
	NSString* _requestErrorDomain;
	SCD_Struct_AW9 _has;

}

@property (assign,nonatomic) BOOL hasTimestamp; 
@property (assign,nonatomic) long long timestamp;                              //@synthesize timestamp=_timestamp - In the implementation block
@property (nonatomic,readonly) BOOL hasClientId; 
@property (nonatomic,retain) NSString * clientId;                              //@synthesize clientId=_clientId - In the implementation block
@property (assign,nonatomic) BOOL hasStartTime; 
@property (assign,nonatomic) long long startTime;                              //@synthesize startTime=_startTime - In the implementation block
@property (assign,nonatomic) BOOL hasDuration; 
@property (assign,nonatomic) long long duration;                               //@synthesize duration=_duration - In the implementation block
@property (nonatomic,readonly) BOOL hasCancelledErrorDomain; 
@property (nonatomic,retain) NSString * cancelledErrorDomain;                  //@synthesize cancelledErrorDomain=_cancelledErrorDomain - In the implementation block
@property (assign,nonatomic) BOOL hasCancelledErrorCode; 
@property (assign,nonatomic) int cancelledErrorCode;                           //@synthesize cancelledErrorCode=_cancelledErrorCode - In the implementation block
@property (nonatomic,readonly) BOOL hasRequestErrorDomain; 
@property (nonatomic,retain) NSString * requestErrorDomain;                    //@synthesize requestErrorDomain=_requestErrorDomain - In the implementation block
@property (assign,nonatomic) BOOL hasRequestErrorCode; 
@property (assign,nonatomic) int requestErrorCode;                             //@synthesize requestErrorCode=_requestErrorCode - In the implementation block
@property (assign,nonatomic) BOOL hasItemCount; 
@property (assign,nonatomic) int itemCount;                                    //@synthesize itemCount=_itemCount - In the implementation block
@property (assign,nonatomic) BOOL hasItemsAlreadyPresentCount; 
@property (assign,nonatomic) int itemsAlreadyPresentCount;                     //@synthesize itemsAlreadyPresentCount=_itemsAlreadyPresentCount - In the implementation block
@property (assign,nonatomic) BOOL hasItemsPartiallyPresentCount; 
@property (assign,nonatomic) int itemsPartiallyPresentCount;                   //@synthesize itemsPartiallyPresentCount=_itemsPartiallyPresentCount - In the implementation block
@property (assign,nonatomic) BOOL hasItemsNotPresentCount; 
@property (assign,nonatomic) int itemsNotPresentCount;                         //@synthesize itemsNotPresentCount=_itemsNotPresentCount - In the implementation block
@property (assign,nonatomic) BOOL hasChunksUploaded; 
@property (assign,nonatomic) int chunksUploaded;                               //@synthesize chunksUploaded=_chunksUploaded - In the implementation block
@property (nonatomic,retain) NSMutableArray * chunkingInfos;                   //@synthesize chunkingInfos=_chunkingInfos - In the implementation block
@property (nonatomic,retain) NSMutableArray * authHttpInfos;                   //@synthesize authHttpInfos=_authHttpInfos - In the implementation block
@property (nonatomic,retain) NSMutableArray * containerHttpInfos;              //@synthesize containerHttpInfos=_containerHttpInfos - In the implementation block
@property (nonatomic,retain) NSMutableArray * completeHttpInfos;               //@synthesize completeHttpInfos=_completeHttpInfos - In the implementation block
@property (nonatomic,retain) NSMutableArray * cancelErrors;                    //@synthesize cancelErrors=_cancelErrors - In the implementation block
@property (nonatomic,retain) NSMutableArray * errors;                          //@synthesize errors=_errors - In the implementation block
-(int)itemCount;
-(void)dealloc;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(long long)timestamp;
-(long long)duration;
-(void)setDuration:(long long)arg1 ;
-(void)setStartTime:(long long)arg1 ;
-(void)setTimestamp:(long long)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)dictionaryRepresentation;
-(long long)startTime;
-(void)mergeFrom:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(BOOL)hasTimestamp;
-(void)setHasTimestamp:(BOOL)arg1 ;
-(void)setHasStartTime:(BOOL)arg1 ;
-(BOOL)hasStartTime;
-(void)setHasRequestErrorCode:(BOOL)arg1 ;
-(void)setRequestErrorDomain:(NSString *)arg1 ;
-(int)requestErrorCode;
-(BOOL)hasRequestErrorCode;
-(BOOL)hasRequestErrorDomain;
-(void)setRequestErrorCode:(int)arg1 ;
-(NSString *)requestErrorDomain;
-(BOOL)hasDuration;
-(void)setHasDuration:(BOOL)arg1 ;
-(BOOL)readFrom:(id)arg1 ;
-(void)setClientId:(NSString *)arg1 ;
-(BOOL)hasClientId;
-(NSString *)clientId;
-(void)setCancelledErrorDomain:(NSString *)arg1 ;
-(void)setAuthHttpInfos:(NSMutableArray *)arg1 ;
-(void)setContainerHttpInfos:(NSMutableArray *)arg1 ;
-(void)setCompleteHttpInfos:(NSMutableArray *)arg1 ;
-(void)setCancelErrors:(NSMutableArray *)arg1 ;
-(void)setErrors:(NSMutableArray *)arg1 ;
-(void)addAuthHttpInfos:(id)arg1 ;
-(void)addContainerHttpInfos:(id)arg1 ;
-(void)addCompleteHttpInfos:(id)arg1 ;
-(void)addCancelError:(id)arg1 ;
-(void)addError:(id)arg1 ;
-(unsigned long long)authHttpInfosCount;
-(void)clearAuthHttpInfos;
-(id)authHttpInfosAtIndex:(unsigned long long)arg1 ;
-(unsigned long long)containerHttpInfosCount;
-(void)clearContainerHttpInfos;
-(id)containerHttpInfosAtIndex:(unsigned long long)arg1 ;
-(unsigned long long)completeHttpInfosCount;
-(void)clearCompleteHttpInfos;
-(id)completeHttpInfosAtIndex:(unsigned long long)arg1 ;
-(unsigned long long)cancelErrorsCount;
-(void)clearCancelErrors;
-(id)cancelErrorAtIndex:(unsigned long long)arg1 ;
-(unsigned long long)errorsCount;
-(void)clearErrors;
-(id)errorAtIndex:(unsigned long long)arg1 ;
-(BOOL)hasCancelledErrorDomain;
-(void)setCancelledErrorCode:(int)arg1 ;
-(void)setHasCancelledErrorCode:(BOOL)arg1 ;
-(BOOL)hasCancelledErrorCode;
-(void)setItemCount:(int)arg1 ;
-(void)setHasItemCount:(BOOL)arg1 ;
-(BOOL)hasItemCount;
-(NSString *)cancelledErrorDomain;
-(int)cancelledErrorCode;
-(NSMutableArray *)authHttpInfos;
-(NSMutableArray *)containerHttpInfos;
-(NSMutableArray *)completeHttpInfos;
-(NSMutableArray *)cancelErrors;
-(NSMutableArray *)errors;
-(void)setChunkingInfos:(NSMutableArray *)arg1 ;
-(void)addChunkingInfos:(id)arg1 ;
-(unsigned long long)chunkingInfosCount;
-(void)clearChunkingInfos;
-(id)chunkingInfosAtIndex:(unsigned long long)arg1 ;
-(void)setItemsAlreadyPresentCount:(int)arg1 ;
-(void)setHasItemsAlreadyPresentCount:(BOOL)arg1 ;
-(BOOL)hasItemsAlreadyPresentCount;
-(void)setItemsPartiallyPresentCount:(int)arg1 ;
-(void)setHasItemsPartiallyPresentCount:(BOOL)arg1 ;
-(BOOL)hasItemsPartiallyPresentCount;
-(void)setItemsNotPresentCount:(int)arg1 ;
-(void)setHasItemsNotPresentCount:(BOOL)arg1 ;
-(BOOL)hasItemsNotPresentCount;
-(void)setChunksUploaded:(int)arg1 ;
-(void)setHasChunksUploaded:(BOOL)arg1 ;
-(BOOL)hasChunksUploaded;
-(int)itemsAlreadyPresentCount;
-(int)itemsPartiallyPresentCount;
-(int)itemsNotPresentCount;
-(int)chunksUploaded;
-(NSMutableArray *)chunkingInfos;
@end

