/*
* This header is generated by classdump-dyld 0.7
* on Sunday, November 22, 2015 at 10:28:27 PM Eastern Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libAWDSupportFramework.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libAWDSupportFramework.dylib/libAWDSupportFramework.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSData;

@interface AWDWifiMostUsedNetworks : PBCodable <NSCopying> {

	double _timeUsed;
	unsigned _apOUI;
	NSData* _apOui;
	unsigned _securityType;
	unsigned _timeUsedMinutes;
	SCD_Struct_AW10 _has;

}

@property (assign,nonatomic) BOOL hasApOUI; 
@property (assign,nonatomic) unsigned apOUI;                        //@synthesize apOUI=_apOUI - In the implementation block
@property (assign,nonatomic) BOOL hasSecurityType; 
@property (assign,nonatomic) unsigned securityType;                 //@synthesize securityType=_securityType - In the implementation block
@property (assign,nonatomic) BOOL hasTimeUsed; 
@property (assign,nonatomic) double timeUsed;                       //@synthesize timeUsed=_timeUsed - In the implementation block
@property (nonatomic,readonly) BOOL hasApOui; 
@property (nonatomic,retain) NSData * apOui;                        //@synthesize apOui=_apOui - In the implementation block
@property (assign,nonatomic) BOOL hasTimeUsedMinutes; 
@property (assign,nonatomic) unsigned timeUsedMinutes;              //@synthesize timeUsedMinutes=_timeUsedMinutes - In the implementation block
-(void)dealloc;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)dictionaryRepresentation;
-(void)mergeFrom:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(BOOL)readFrom:(id)arg1 ;
-(void)setSecurityType:(unsigned)arg1 ;
-(void)setHasSecurityType:(BOOL)arg1 ;
-(BOOL)hasSecurityType;
-(unsigned)securityType;
-(void)setApOui:(NSData *)arg1 ;
-(void)setApOUI:(unsigned)arg1 ;
-(void)setHasApOUI:(BOOL)arg1 ;
-(BOOL)hasApOUI;
-(void)setTimeUsed:(double)arg1 ;
-(void)setHasTimeUsed:(BOOL)arg1 ;
-(BOOL)hasTimeUsed;
-(BOOL)hasApOui;
-(void)setTimeUsedMinutes:(unsigned)arg1 ;
-(void)setHasTimeUsedMinutes:(BOOL)arg1 ;
-(BOOL)hasTimeUsedMinutes;
-(unsigned)apOUI;
-(double)timeUsed;
-(NSData *)apOui;
-(unsigned)timeUsedMinutes;
@end

