#import <libAWDSupportFramework.dylib/AWDAirPlayAudioSessionEndedOnClient.h>
#import <libAWDSupportFramework.dylib/AWDAirPlayAudioSessionEndedOnServer.h>
#import <libAWDSupportFramework.dylib/AWDAirPlayAudioSessionStartedOnClient.h>
#import <libAWDSupportFramework.dylib/AWDAirPlayAudioSessionStartedOnServer.h>
#import <libAWDSupportFramework.dylib/AWDAirPlayPhotoSessionEndedOnClient.h>
#import <libAWDSupportFramework.dylib/AWDAirPlayPhotoSessionEndedOnServer.h>
#import <libAWDSupportFramework.dylib/AWDAirPlayPhotoSessionStartedOnClient.h>
#import <libAWDSupportFramework.dylib/AWDAirPlayPhotoSessionStartedOnServer.h>
#import <libAWDSupportFramework.dylib/AWDAirPlayScreenSessionEndedOnClient.h>
#import <libAWDSupportFramework.dylib/AWDAirPlayScreenSessionEndedOnServer.h>
#import <libAWDSupportFramework.dylib/AWDAirPlayScreenSessionStartedOnClient.h>
#import <libAWDSupportFramework.dylib/AWDAirPlayScreenSessionStartedOnServer.h>
#import <libAWDSupportFramework.dylib/AWDAirPlaySessionEnded.h>
#import <libAWDSupportFramework.dylib/AWDAirPlaySessionStarted.h>
#import <libAWDSupportFramework.dylib/AWDAirPlaySlideshowSessionEndedOnClient.h>
#import <libAWDSupportFramework.dylib/AWDAirPlaySlideshowSessionEndedOnServer.h>
#import <libAWDSupportFramework.dylib/AWDAirPlaySlideshowSessionStartedOnClient.h>
#import <libAWDSupportFramework.dylib/AWDAirPlaySlideshowSessionStartedOnServer.h>
#import <libAWDSupportFramework.dylib/AWDAirPlayVideoSessionEndedOnClient.h>
#import <libAWDSupportFramework.dylib/AWDAirPlayVideoSessionEndedOnServer.h>
#import <libAWDSupportFramework.dylib/AWDAirPlayVideoSessionStartedOnClient.h>
#import <libAWDSupportFramework.dylib/AWDAirPlayVideoSessionStartedOnServer.h>
#import <libAWDSupportFramework.dylib/AWDBltDelayToPrimaryDevice.h>
#import <libAWDSupportFramework.dylib/AWDBltDelayToSecondaryDevice.h>
#import <libAWDSupportFramework.dylib/AWDBltPrimaryDevicePublicationToResponseDelay.h>
#import <libAWDSupportFramework.dylib/AWDBltPrimaryDeviceSendAttempt.h>
#import <libAWDSupportFramework.dylib/AWDBltPrimaryDeviceSendInTime.h>
#import <libAWDSupportFramework.dylib/AWDBltPrimaryDeviceSendTimeout.h>
#import <libAWDSupportFramework.dylib/AWDBltRequestToResponseDelay.h>
#import <libAWDSupportFramework.dylib/AWDBltSecondaryConnectedToTransport.h>
#import <libAWDSupportFramework.dylib/AWDBltSecondaryProcessStarted.h>
#import <libAWDSupportFramework.dylib/AWDBltUIBuildAttempt.h>
#import <libAWDSupportFramework.dylib/AWDBltUIBuildFail.h>
#import <libAWDSupportFramework.dylib/AWDBltUIBuildSuccess.h>
#import <libAWDSupportFramework.dylib/AWDCallHistoryCallAddedBeforeUnlock.h>
#import <libAWDSupportFramework.dylib/AWDCallHistoryCommCenterMigration.h>
#import <libAWDSupportFramework.dylib/AWDCallHistoryDatabaseInfo.h>
#import <libAWDSupportFramework.dylib/AWDCallHistoryDatabaseMigration.h>
#import <libAWDSupportFramework.dylib/AWDCallHistoryDatabaseSaveError.h>
#import <libAWDSupportFramework.dylib/AWDCallHistoryDeleteAll.h>
#import <libAWDSupportFramework.dylib/AWDCallHistoryDeviceUnlocked.h>
#import <libAWDSupportFramework.dylib/AWDCallHistoryEntitlementRejection.h>
#import <libAWDSupportFramework.dylib/AWDCallHistoryErrorReport.h>
#import <libAWDSupportFramework.dylib/AWDCallHistoryGizmoBootstrap.h>
#import <libAWDSupportFramework.dylib/AWDCallHistoryGizmoDatabaseMigrationFailure.h>
#import <libAWDSupportFramework.dylib/AWDCallHistoryMalformedCloudChangeToken.h>
#import <libAWDSupportFramework.dylib/AWDCallHistoryMissingCloudChangeToken.h>
#import <libAWDSupportFramework.dylib/AWDCallHistoryNilUuid.h>
#import <libAWDSupportFramework.dylib/AWDCallHistorySync.h>
#import <libAWDSupportFramework.dylib/AWDCallHistorySyncOverLimit.h>
#import <libAWDSupportFramework.dylib/AWDCallHistoryTransactionLogSize.h>
#import <libAWDSupportFramework.dylib/AWDCallHistoryUninitializedDatabaseSave.h>
#import <libAWDSupportFramework.dylib/AWDCSDRelayMessageReceived.h>
#import <libAWDSupportFramework.dylib/AWDCaptiveSession.h>
#import <libAWDSupportFramework.dylib/AWDCFNetworkW3CNavigationTiming.h>
#import <libAWDSupportFramework.dylib/AWDCompanionSyncErrorEvent.h>
#import <libAWDSupportFramework.dylib/AWDCompanionSyncErrorNotification.h>
#import <libAWDSupportFramework.dylib/AWDCompanionSyncFullSyncDuration.h>
#import <libAWDSupportFramework.dylib/AWDCompanionSyncReceiveEvent.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineHintSourceSubmissionInstance.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineHintSourceSubmissionSet.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineHintSourceUsageInstance.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineHintSourceUsageSet.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineMagicalMomentsIndividualMoment.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineMagicalMomentsRecommendedAppsHistogramInstance.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineMagicalMomentsRecommendedAppsHistogramSet.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineModelAlgorithmInstance.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineModelAlgorithmSet.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineModelAvailability.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineModelClusterMovementInstance.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineModelClusterMovementNoiseSet.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineModelClusterStandardDeviationInstance.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineModelClusterStandardDeviationSet.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineModelConsistencyReconsolidation.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineModelDominantPlaceCount.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineModelLearnedNonGeocodeableEvents.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineModelLength.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineModelStatus.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineModelTransitionInstance.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineModelTransitionSet.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineModelVisitCount.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineStateModelConfidence.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineTransitionMotionType.h>
#import <libAWDSupportFramework.dylib/AWDEasyConfigCompleted.h>
#import <libAWDSupportFramework.dylib/AWDEventKitSyncCompletedNightlySync.h>
#import <libAWDSupportFramework.dylib/AWDEventKitSyncIsNotifiableEvent.h>
#import <libAWDSupportFramework.dylib/AWDEventKitSyncSyncedAttendeeResponseFromWatch.h>
#import <libAWDSupportFramework.dylib/AWDEventKitSyncSyncedEventCreatedOnWatch.h>
#import <libAWDSupportFramework.dylib/AWDEventKitSyncSyncedTaskCreatedOnWatch.h>
#import <libAWDSupportFramework.dylib/AWDFaceTimeCallAcceptReceived.h>
#import <libAWDSupportFramework.dylib/AWDFaceTimeCallAcceptSent.h>
#import <libAWDSupportFramework.dylib/AWDFaceTimeCallCancelSent.h>
#import <libAWDSupportFramework.dylib/AWDFaceTimeCallConnected.h>
#import <libAWDSupportFramework.dylib/AWDFaceTimeCallDeclineSent.h>
#import <libAWDSupportFramework.dylib/AWDFaceTimeCallEnded.h>
#import <libAWDSupportFramework.dylib/AWDFaceTimeCallFailed.h>
#import <libAWDSupportFramework.dylib/AWDFaceTimeCallInterruptionBegan.h>
#import <libAWDSupportFramework.dylib/AWDFaceTimeCallInterruptionEnded.h>
#import <libAWDSupportFramework.dylib/AWDFaceTimeCallInvitationReceived.h>
#import <libAWDSupportFramework.dylib/AWDFaceTimeCallInvitationSent.h>
#import <libAWDSupportFramework.dylib/AWDFaceTimeCallRelayInitiateReceived.h>
#import <libAWDSupportFramework.dylib/AWDFaceTimeCallRelayInitiateSent.h>
#import <libAWDSupportFramework.dylib/AWDFaceTimeCallRelayUpdateReceived.h>
#import <libAWDSupportFramework.dylib/AWDFaceTimeCallRelayUpdateSent.h>
#import <libAWDSupportFramework.dylib/AWDFaceTimeCallStarted.h>
#import <libAWDSupportFramework.dylib/AWDHealthKitActivityRingEvent.h>
#import <libAWDSupportFramework.dylib/AWDHealthKitCoachingEvent.h>
#import <libAWDSupportFramework.dylib/AWDHealthKitCoachingFeatureGroup.h>
#import <libAWDSupportFramework.dylib/AWDHealthKitCoachingFeatures.h>
#import <libAWDSupportFramework.dylib/AWDHomeKitConfiguration.h>
#import <libAWDSupportFramework.dylib/AWDHomeKitEvent.h>
#import <libAWDSupportFramework.dylib/AWDHomeKitRemoteSession.h>
#import <libAWDSupportFramework.dylib/AWDHomeKitResult.h>
#import <libAWDSupportFramework.dylib/AWDHoneybeeSignature.h>
#import <libAWDSupportFramework.dylib/AWDIDSAppDeliveryReceipt.h>
#import <libAWDSupportFramework.dylib/AWDIDSClientProcessReceivedMessage.h>
#import <libAWDSupportFramework.dylib/AWDIDSLocalDeliveryAppLevelAck.h>
#import <libAWDSupportFramework.dylib/AWDIDSLocalDeliveryMessageDelivered.h>
#import <libAWDSupportFramework.dylib/AWDIDSLocalDeliveryMessageReceived.h>
#import <libAWDSupportFramework.dylib/AWDIDSLocalDeliveryMessageSent.h>
#import <libAWDSupportFramework.dylib/AWDIDSLocalDeliverySocketClosed.h>
#import <libAWDSupportFramework.dylib/AWDIDSLocalDeliverySocketOpened.h>
#import <libAWDSupportFramework.dylib/AWDIDSLocalMessageRTT.h>
#import <libAWDSupportFramework.dylib/AWDIDSLocalMessageTimedOut.h>
#import <libAWDSupportFramework.dylib/AWDIDSMagnetCorruption.h>
#import <libAWDSupportFramework.dylib/AWDIDSOTRSessionNegotiation.h>
#import <libAWDSupportFramework.dylib/AWDIDSRegistrationAuthenticate.h>
#import <libAWDSupportFramework.dylib/AWDIDSRegistrationOperation.h>
#import <libAWDSupportFramework.dylib/AWDIDSRegistrationPhoneNumberReceivedSMS.h>
#import <libAWDSupportFramework.dylib/AWDIDSRegistrationPhoneNumberValidationFinished.h>
#import <libAWDSupportFramework.dylib/AWDIDSRegistrationProfileHandleOperation.h>
#import <libAWDSupportFramework.dylib/AWDIDSRegistrationProfileOperation.h>
#import <libAWDSupportFramework.dylib/AWDIDSSessionEnded.h>
#import <libAWDSupportFramework.dylib/AWDIDSStreamingReport.h>
#import <libAWDSupportFramework.dylib/AWDIDSWRMLinkRecommendation.h>
#import <libAWDSupportFramework.dylib/AWDIDSWiFiSetupAttempt.h>
#import <libAWDSupportFramework.dylib/AWDIDSWiProxConnectionFailed.h>
#import <libAWDSupportFramework.dylib/AWDIDSWiProxConnectionSuccess.h>
#import <libAWDSupportFramework.dylib/AWDIMessageAttachmentDownload.h>
#import <libAWDSupportFramework.dylib/AWDIMessageAttachmentUpload.h>
#import <libAWDSupportFramework.dylib/AWDIMessageDeduplicated.h>
#import <libAWDSupportFramework.dylib/AWDIMessageDeliveredMessage.h>
#import <libAWDSupportFramework.dylib/AWDIMessageDowngrade.h>
#import <libAWDSupportFramework.dylib/AWDIMessageQueryFinished.h>
#import <libAWDSupportFramework.dylib/AWDIMessageReceivedMessage.h>
#import <libAWDSupportFramework.dylib/AWDIMessageSentMessage.h>
#import <libAWDSupportFramework.dylib/AWDSMSReceivedMessage.h>
#import <libAWDSupportFramework.dylib/AWDSMSSentMessage.h>
#import <libAWDSupportFramework.dylib/AWDIMRemoteURLLoadCompleted.h>
#import <libAWDSupportFramework.dylib/AWDIMRemoteURLLoadFailed.h>
#import <libAWDSupportFramework.dylib/AWDITesterAppStart.h>
#import <libAWDSupportFramework.dylib/AWDITesterApplicationUUID.h>
#import <libAWDSupportFramework.dylib/AWDITesterApplyCustomInputs.h>
#import <libAWDSupportFramework.dylib/AWDITesterTestFinish.h>
#import <libAWDSupportFramework.dylib/AWDITesterTestLoad.h>
#import <libAWDSupportFramework.dylib/AWDITesterTestShare.h>
#import <libAWDSupportFramework.dylib/AWDITesterTestStart.h>
#import <libAWDSupportFramework.dylib/AWDLBClientConnectionReport.h>
#import <libAWDSupportFramework.dylib/AWDLBConnectionReport.h>
#import <libAWDSupportFramework.dylib/AWDLBEndpointsFetchReport.h>
#import <libAWDSupportFramework.dylib/AWDLibnetcoreCellularFallbackReport.h>
#import <libAWDSupportFramework.dylib/AWDLibnetcoreConnectionDataUsageSnapshot.h>
#import <libAWDSupportFramework.dylib/AWDLibnetcoreConnectionStatisticsReport.h>
#import <libAWDSupportFramework.dylib/AWDLibnetcoreMbufStatsReport.h>
#import <libAWDSupportFramework.dylib/AWDLibnetcoreNetworkdStatsReport.h>
#import <libAWDSupportFramework.dylib/AWDLibnetcoreStatsReport.h>
#import <libAWDSupportFramework.dylib/AWDLibnetcoreTCPConnectionReport.h>
#import <libAWDSupportFramework.dylib/AWDLibnetcoreTCPECNStatsReport.h>
#import <libAWDSupportFramework.dylib/AWDLibnetcoreTCPKernelStats.h>
#import <libAWDSupportFramework.dylib/AWDLibnetcoreTCPStatsReport.h>
#import <libAWDSupportFramework.dylib/AWDLibnetcoreTCPTFOStatsReport.h>
#import <libAWDSupportFramework.dylib/AWDMPTCPConnectionInterfaceReport.h>
#import <libAWDSupportFramework.dylib/AWDMPTCPConnectionReport.h>
#import <libAWDSupportFramework.dylib/AWDMPTCPSubflowSwitchingReport.h>
#import <libAWDSupportFramework.dylib/AWDMMCSChunkingInfo.h>
#import <libAWDSupportFramework.dylib/AWDMMCSError.h>
#import <libAWDSupportFramework.dylib/AWDMMCSGetRequestInfo.h>
#import <libAWDSupportFramework.dylib/AWDMMCSHttpInfo.h>
#import <libAWDSupportFramework.dylib/AWDMMCSPutRequestInfo.h>
#import <libAWDSupportFramework.dylib/AWDMMCSTcpInfo.h>
#import <libAWDSupportFramework.dylib/AWDNanoRegistryPairingAttemptReport.h>
#import <libAWDSupportFramework.dylib/AWDNFCCRSAuthExceptionEvent.h>
#import <libAWDSupportFramework.dylib/AWDNFCCRSAuthInitExceptionEvent.h>
#import <libAWDSupportFramework.dylib/AWDNFCDeviceExceptionStatistic.h>
#import <libAWDSupportFramework.dylib/AWDNFCFieldOffEvent.h>
#import <libAWDSupportFramework.dylib/AWDNFCFieldOnEvent.h>
#import <libAWDSupportFramework.dylib/AWDNFCGeneralStatistic.h>
#import <libAWDSupportFramework.dylib/AWDNFCHCEVASGetData.h>
#import <libAWDSupportFramework.dylib/AWDNFCHCEVASSelectEvent.h>
#import <libAWDSupportFramework.dylib/AWDNFCHCIEndOfTransactionEvent.h>
#import <libAWDSupportFramework.dylib/AWDNFCHCIEndOfTransactionExceptionEvent.h>
#import <libAWDSupportFramework.dylib/AWDNFCHCIStartOfTransactionEvent.h>
#import <libAWDSupportFramework.dylib/AWDNFCHCIStartOfTransactionExceptionEvent.h>
#import <libAWDSupportFramework.dylib/AWDNFCHardwareExceptionEvent.h>
#import <libAWDSupportFramework.dylib/AWDNFCIncompleteTransactionExceptionEvent.h>
#import <libAWDSupportFramework.dylib/AWDNFCJCOPRestrictedModeEvent.h>
#import <libAWDSupportFramework.dylib/AWDNFCMiddlewareExceptionEvent.h>
#import <libAWDSupportFramework.dylib/AWDNFCSEAIDSelectEvent.h>
#import <libAWDSupportFramework.dylib/AWDNFCSECRSAuthInit.h>
#import <libAWDSupportFramework.dylib/AWDNFCSECRSAuthorize.h>
#import <libAWDSupportFramework.dylib/AWDNFCSECRSAuthorizeECommerce.h>
#import <libAWDSupportFramework.dylib/AWDNFCSERemovedEvent.h>
#import <libAWDSupportFramework.dylib/AWDNFCTSMAPNReceivedEvent.h>
#import <libAWDSupportFramework.dylib/AWDNFCTSMConnectEvent.h>
#import <libAWDSupportFramework.dylib/AWDNFCTSMConnectivityExceptionEvent.h>
#import <libAWDSupportFramework.dylib/AWDNFCTSMEndEvent.h>
#import <libAWDSupportFramework.dylib/AWDNFCTSMStartEvent.h>
#import <libAWDSupportFramework.dylib/AWDNFCTransactionEndOfOperationEvent.h>
#import <libAWDSupportFramework.dylib/AWDNFCTransactionLastAPDUSentEvent.h>
#import <libAWDSupportFramework.dylib/AWDNFCVASTransactionExceptionEvent.h>
#import <libAWDSupportFramework.dylib/AWDNFCVersions.h>
#import <libAWDSupportFramework.dylib/AWDAppBBPower.h>
#import <libAWDSupportFramework.dylib/AWDAppRRCConnectionStats.h>
#import <libAWDSupportFramework.dylib/AWDBacklightLuxMicroAmpsBucket.h>
#import <libAWDSupportFramework.dylib/AWDBasebandPowerToolKPIs.h>
#import <libAWDSupportFramework.dylib/AWDCpuLoad.h>
#import <libAWDSupportFramework.dylib/AWDLQMDataTransfer.h>
#import <libAWDSupportFramework.dylib/AWDNetworkUsage.h>
#import <libAWDSupportFramework.dylib/AWDPowerApMetrics.h>
#import <libAWDSupportFramework.dylib/AWDPowerAppBBMetrics.h>
#import <libAWDSupportFramework.dylib/AWDPowerAudioMetrics.h>
#import <libAWDSupportFramework.dylib/AWDPowerBBAppRRCMetrics.h>
#import <libAWDSupportFramework.dylib/AWDPowerBBCallMetricInfo.h>
#import <libAWDSupportFramework.dylib/AWDPowerBBCallMetrics.h>
#import <libAWDSupportFramework.dylib/AWDPowerBBLQMDataTransferMetrics.h>
#import <libAWDSupportFramework.dylib/AWDPowerBBNonDataMetrics.h>
#import <libAWDSupportFramework.dylib/AWDPowerBBRATConnectedMetrics.h>
#import <libAWDSupportFramework.dylib/AWDPowerBatteryMetrics.h>
#import <libAWDSupportFramework.dylib/AWDPowerBluetoothMetrics.h>
#import <libAWDSupportFramework.dylib/AWDPowerCameraMetrics.h>
#import <libAWDSupportFramework.dylib/AWDPowerDisplayBacklightMetrics.h>
#import <libAWDSupportFramework.dylib/AWDPowerNetworkUsageMetrics.h>
#import <libAWDSupportFramework.dylib/AWDPowerPerProcessCPULoadMetrics.h>
#import <libAWDSupportFramework.dylib/AWDPowerStateResidencyAndWeight.h>
#import <libAWDSupportFramework.dylib/AWDPowerTouchMetrics.h>
#import <libAWDSupportFramework.dylib/AWDPowerWifiMetrics.h>
#import <libAWDSupportFramework.dylib/AWDRATConnectedPower.h>
#import <libAWDSupportFramework.dylib/AWDPushConnectionConnected.h>
#import <libAWDSupportFramework.dylib/AWDPushConnectionDisconnected.h>
#import <libAWDSupportFramework.dylib/AWDPushKeepAliveFailed.h>
#import <libAWDSupportFramework.dylib/AWDPushKeepAliveSent.h>
#import <libAWDSupportFramework.dylib/AWDPushReceived.h>
#import <libAWDSupportFramework.dylib/AWDPushReceivedDropped.h>
#import <libAWDSupportFramework.dylib/AWDPushReceivedSlow.h>
#import <libAWDSupportFramework.dylib/AWDPushSent.h>
#import <libAWDSupportFramework.dylib/AWDSafariPageLoadCompleteEvent.h>
#import <libAWDSupportFramework.dylib/AWDSafariPageLoadStartedEvent.h>
#import <libAWDSupportFramework.dylib/AWDSiriNetworkAnalyzerRun.h>
#import <libAWDSupportFramework.dylib/AWDSiriServerConnectionFailed.h>
#import <libAWDSupportFramework.dylib/AWDSiriServerConnectionOpen.h>
#import <libAWDSupportFramework.dylib/AWDSiriServerConnectionStart.h>
#import <libAWDSupportFramework.dylib/AWDSiriSessionLoadTimeout.h>
#import <libAWDSupportFramework.dylib/AWDSiriSpeechRecognized.h>
#import <libAWDSupportFramework.dylib/AWDSiriVoiceRecordingEnd.h>
#import <libAWDSupportFramework.dylib/AWDSiriVoiceRecordingStart.h>
#import <libAWDSupportFramework.dylib/AWDSiriVoiceSendEnd.h>
#import <libAWDSupportFramework.dylib/AWDSiriVoiceSendStart.h>
#import <libAWDSupportFramework.dylib/AWDSymptomsAdvisoryAlternateNetworkType.h>
#import <libAWDSupportFramework.dylib/AWDSymptomsNetworkAnalyticsDNSRestored.h>
#import <libAWDSupportFramework.dylib/AWDSymptomsNetworkAnalyticsDNSTotalFailure.h>
#import <libAWDSupportFramework.dylib/AWDSymptomsNetworkAnalyticsHistorical.h>
#import <libAWDSupportFramework.dylib/AWDSymptomsNetworkAnalyticsInstant.h>
#import <libAWDSupportFramework.dylib/AWDSymptomsNetworkAnalyticsPredictions.h>
#import <libAWDSupportFramework.dylib/AWDSymptomsNetworkAnalyticsRRCConnectedPeriod.h>
#import <libAWDSupportFramework.dylib/AWDSymptomsNetworkAnalyticsScoring.h>
#import <libAWDSupportFramework.dylib/AWDVPNSession.h>
#import <libAWDSupportFramework.dylib/AWDChipCountersRx.h>
#import <libAWDSupportFramework.dylib/AWDChipCountersTx.h>
#import <libAWDSupportFramework.dylib/AWDChipErrorCountersTx.h>
#import <libAWDSupportFramework.dylib/AWDControlFrames.h>
#import <libAWDSupportFramework.dylib/AWDDataFrames.h>
#import <libAWDSupportFramework.dylib/AWDMacCountersRx.h>
#import <libAWDSupportFramework.dylib/AWDMacCountersRxErrors.h>
#import <libAWDSupportFramework.dylib/AWDManagementFrames.h>
#import <libAWDSupportFramework.dylib/AWDRxPhyErrors.h>
#import <libAWDSupportFramework.dylib/AWDWPA2Counters.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricActiveProbeStats.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricCustomNetworkSetting.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricHotspotTransportType.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricIPv4DHCPLatency.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricInterfaceStats.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricLinkChangeData.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricNetworkPrefs.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricRssiHistory.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricWowState.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsKnownNetworksEvent.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsManagerAwdlUsage.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsManagerBTCoexModeChange.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsManagerBTCoexStats.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsManagerChipCounters.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsManagerChipMemory.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsManagerDeviceCount.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsManagerEvent.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsManagerFrameCounterStats.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsManagerInfraInterface.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsManagerLeakyAPStats.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsManagerLinkQualityStats.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsManagerPowerStatsUpdateEvent.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsManagerStateMachine.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsManagerWatchdogEvent.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsManagerWifidAvailability.h>
#import <libAWDSupportFramework.dylib/AWDWifiAssociation.h>
#import <libAWDSupportFramework.dylib/AWDWifiAwdlServiceRecord.h>
#import <libAWDSupportFramework.dylib/AWDWifiAwdlStateInfo.h>
#import <libAWDSupportFramework.dylib/AWDWifiHardwareVersion.h>
#import <libAWDSupportFramework.dylib/AWDWifiLinkQualityRecord.h>
#import <libAWDSupportFramework.dylib/AWDWifiMetricWiFiTetheredDeviceOUI.h>
#import <libAWDSupportFramework.dylib/AWDWifiMostUsedNetworks.h>
#import <libAWDSupportFramework.dylib/AWDWifiPowerState.h>
#import <libAWDSupportFramework.dylib/AWDWifiCallingCallEndReport.h>
#import <libAWDSupportFramework.dylib/AWDWiProxBluetoothState.h>
#import <libAWDSupportFramework.dylib/AWDWiProxLeAddServiceRequest.h>
#import <libAWDSupportFramework.dylib/AWDWiProxLeAddServiceResult.h>
#import <libAWDSupportFramework.dylib/AWDWiProxLeAdvertiseStartRequest.h>
#import <libAWDSupportFramework.dylib/AWDWiProxLeAdvertiseStartResult.h>
#import <libAWDSupportFramework.dylib/AWDWiProxLeAdvertiseStopRequest.h>
#import <libAWDSupportFramework.dylib/AWDWiProxLeAdvertiseStopResult.h>
#import <libAWDSupportFramework.dylib/AWDWiProxLeBeaconDiscovered.h>
#import <libAWDSupportFramework.dylib/AWDWiProxLeConnectionRequest.h>
#import <libAWDSupportFramework.dylib/AWDWiProxLeConnectionResult.h>
#import <libAWDSupportFramework.dylib/AWDWiProxLeDeviceDiscovered.h>
#import <libAWDSupportFramework.dylib/AWDWiProxLeDeviceLost.h>
#import <libAWDSupportFramework.dylib/AWDWiProxLeDisconnectionRequest.h>
#import <libAWDSupportFramework.dylib/AWDWiProxLeDisconnectionResult.h>
#import <libAWDSupportFramework.dylib/AWDWiProxLeReceiveDataResult.h>
#import <libAWDSupportFramework.dylib/AWDWiProxLeRemoveServiceRequest.h>
#import <libAWDSupportFramework.dylib/AWDWiProxLeScanStartRequest.h>
#import <libAWDSupportFramework.dylib/AWDWiProxLeScanStartResult.h>
#import <libAWDSupportFramework.dylib/AWDWiProxLeScanStopRequest.h>
#import <libAWDSupportFramework.dylib/AWDWiProxLeScanStopResult.h>
#import <libAWDSupportFramework.dylib/AWDWiProxLeSendDataRequest.h>
#import <libAWDSupportFramework.dylib/AWDWiProxLeSendDataResult.h>
#import <libAWDSupportFramework.dylib/AWDWiProxLeStartTrackingPeerResult.h>
#import <libAWDSupportFramework.dylib/AWDWiProxLeStopTrackingPeerResult.h>
#import <libAWDSupportFramework.dylib/AWDWRMLinkPrefChange1.h>
#import <libAWDSupportFramework.dylib/AWDWRMLinkPrefChange2.h>
#import <libAWDSupportFramework.dylib/AWDWRMLinkPrefInit.h>
#import <libAWDSupportFramework.dylib/AWDWRMWiFiCallingEnd.h>
