/*
* This header is generated by classdump-dyld 0.7
* on Sunday, November 22, 2015 at 10:28:28 PM Eastern Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libTelephonyUtilDynamic.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

typedef struct weak_ptr<ctu::Http::URLConnectionCallbackHandler> {
	URLConnectionCallbackHandler __ptr_;
	__shared_weak_count __cntrl_;
} weak_ptr<ctu::Http::URLConnectionCallbackHandler>;

typedef struct shared_ptr<ctu::Http::HttpResponse> {
	HttpResponse __ptr_;
	__shared_weak_count __cntrl_;
} shared_ptr<ctu::Http::HttpResponse>;

